### ISSUE TITLE
SQL parser issue - Snowflake dialect

### ISSUE THREAD

**Issue by prabhur** [TobikoData/sqlmesh#1008]
sqlmesh was unable to execute `sqlmesh plan`. 
The underlying cause was a SQL query with this form.

`select current_timestamp::TIMESTAMP_NTZ(9) last_refreshed_date;`

This is on snowflake. Snowflake does consider this query valid.

```
LAST_REFRESHED_DATE
2023-06-18T19:26:45.404Z
```

Could this be fixed in both sqlgot and sqlmesh? Thanks!

**Comment by tobymao** [comment]
can you provide a bit more detail? did you have a model dialect specified? what was the error in snowflake?

**Comment by prabhur** [comment]
My bad. After reading through the docs, I added the following directive to the `config.yaml` and it is now able to parse the query fine.

```
model_defaults:
    dialect: snowflake
```

I will close this issue. Appreciate the quick response.
