### ISSUE TITLE
Feature request: Make `state` schema configurable

### ISSUE THREAD

**Issue by wseaton** [TobikoData/sqlmesh#1024]
Really a small nit, but it would be a nice enhancement if the schema that sqlmesh uses for state tracking could be overridden globally and/or stored as part of the connection config. Maybe an environment variable could be used instead of a library constant? 

Admittedly the use-case for this is self-inflicted, we are using Trino backed by a hive catalog and the ranger policy we've chosen requires a specific prefix on schema create for user level r/w in dev, ie. `sdbx_*`

**Comment by izeigerman** [comment]
@eakmanrq has this been addressed in https://github.com/TobikoData/sqlmesh/pull/1171? Please close if so

**Comment by eakmanrq** [comment]
Documented in this PR: https://github.com/TobikoData/sqlmesh/pull/1236
