### ISSUE TITLE
Allow creation of Breaking snapshots that have paused Forward-only parents

### ISSUE THREAD

**Issue by izeigerman** [TobikoData/sqlmesh#104]
The Breaking snapshot must target the production version of the table, which the actual parent Forward-only snapshot hasn't been applied to yet (due to it being paused).  Right now we raise an exception if a user attempts to create such a scenario since the production table doesn't reflect schema changes that could've been made in the parent Forward-only snapshot.

The alternative to raising an exception is adding a translation layer, in a form of either a view or a sub-query within the model query, which provides a SELECT projection on top of the production table and which performs transformations necessary to  bring the schema of the production table in correspondence with the schema of the paused Forward-only parent snapshot. 

This would allow the platform to correctly backfill and promote the Breaking snapshot even before its direct Forward-only parent is unpaused.

**Comment by tobymao** [comment]
@izeigerman is this still applicable?
