### ISSUE TITLE
behavior of create_external_models subcommand is not intuitive

### ISSUE THREAD

**Issue by zzztimbo** [TobikoData/sqlmesh#1132]
Given:
- an existing 'schema.yaml` file 
- a new external source is specified in a model that does not exist in the `schema.yaml file

When: 
- `sqlmesh create_external_models` is run

Then: 
- the new sources are added to `schema.yaml` but the previous sources are all removed

My expectation is that the new sources would be added to the existing `schema.yaml` and the old sources would remain as well. 
The mitigating action here is to first delete the schema.yaml before running the command.

**Comment by tobymao** [comment]
thanks, i can fix this hopefully soon
