### ISSUE TITLE
Quickstart guide is missing `--promote-all` flag

### ISSUE THREAD

**Issue by andehen** [TobikoData/sqlmesh#1165]
https://github.com/TobikoData/sqlmesh/blob/4951ff9b539c42242050617869127764d120cf6d/docs/quickstart/cli.md?plain=1#L86

When following the quick start guide, the command `sqlmesh plan dev` fails and does not match the documentation

```
sqlmesh-test-project % sqlmesh plan dev
======================================================================
Successfully Ran 1 tests against duckdb
----------------------------------------------------------------------
Error: No changes were detected. Make a change or run with --promote-all to create a new environment without changes.
```

Running `sqlmesh plan dev --promote-all` works.

**Comment by treysp** [comment]
Thanks for reporting this!
