### ISSUE TITLE
Make `@this_model` available in models

### ISSUE THREAD

**Issue by treysp** [TobikoData/sqlmesh#1215]
Currently `@this_model` is only available in audit definitions, but it would be useful in models as well

**Comment by tobymao** [comment]
there's no need to use @this_model, you can just use the model name

**Comment by z3z1ma** [comment]
@tobymao it is missing the case of using the model name in pre or post hooks which is one of the more useful locations.

**Comment by tobymao** [comment]
you can already do that though? i think this issue doesn't make sense, i'm going to close it

**Comment by treysp** [comment]
For posterity, I believe the original motivation was for macros that generated hooks. 

With this you could write the macro with no explicit parameters and it would work everywhere, but it's easy enough to have model name as a macro parameter and include that in the call.
