### ISSUE TITLE
Add Presto/Trino Support

### ISSUE THREAD

**Issue by eakmanrq** [TobikoData/sqlmesh#124]

**Comment by wseaton** [comment]
Hey folks, I'm available to work on this if needed.

**Comment by tobymao** [comment]
hey @wseaton sorry for the delayed response. we'd love some help on this, let's chat on slack?

**Comment by kmanamcheri** [comment]
I can help test this if needed. From the little code I saw, sqlglot already supports Trino dialect. Is the work here mostly just getting the configuration things set up?

**Comment by tobymao** [comment]
@kmanamcheri yes, it's just in adding an engine_adapter for trino

**Comment by AnirudhVyas** [comment]
Whats the help needed with this? I can help out if needed to get this out - please let me know if that is the reason this was backlogged (lack of resources)

**Comment by tobymao** [comment]
@AnirudhVyas i don't know if anyone is really working on this

**Comment by AnirudhVyas** [comment]
let me figure out whats needed - can you point me in right direction as to what is needed and expected? I'd like to get this in - we would love SQLMesh to support trino.

**Comment by tobymao** [comment]
@AnirudhVyas join our slack and i can help walk you through what's needed https://tobikodata.com/slack

**Comment by tobymao** [comment]
closing this now that trino support has been added, can make new tickets for additional enhancenments
