### ISSUE TITLE
Resolve @DEF values recursively

### ISSUE THREAD

**Issue by izeigerman** [TobikoData/sqlmesh#1252]
Current it's not allowed to reference already defined variables as part of a new variable value. For example the following example is not supported presently:
```sql
@DEF(var_data_cutoff, DATE_SUB(CURRENT_DATE(), INTERVAL 93 DAY));

@DEF(var_cutoff_date,
    (
        SELECT IFNULL(MAX(original_report_date), @var_data_cutoff) AS max_report_date
        FROM `<some_table>`
        WHERE original_report_date >= @var_data_cutoff
    )
);
```

We should make sure that variables are resolved recursively based on variables available in scope at the time of assignment.

**Comment by izeigerman** [comment]
CC: @GeorgeSittas and @tobymao

**Comment by GeorgeSittas** [comment]
Can take a look at this soon 👍
