### ISSUE TITLE
Support Athena

### ISSUE THREAD

**Issue by nicor88** [TobikoData/sqlmesh#1315]
Support for AWS Athena as adapter.

Happy to propose a PR - given some guidelines.

**Comment by tobymao** [comment]
We don't have plans for this right now, but we're happy to accept a PR.

Come join [tobikodata.com/slack](url) to chat with us about it.

Going to close this in favor of https://github.com/TobikoData/sqlmesh/issues/124, but again, happy to help guide you through a pr.

**Comment by nicor88** [comment]
@tobymao Athena is based on trino/presto - but there are some internal differences that make the difference. 
see for example https://github.com/dbt-athena/dbt-athena and https://github.com/starburstdata/dbt-trino
Most of the SQL commands, but how the connection is created and how the result is return back from athena is quite different from trino - I still suggest to keep this as another "issue" ;)

**Comment by tobymao** [comment]
ok sounds good

**Comment by alvaro-ponce** [comment]
hi! I am here just wondering how is this feature going on, I am currently giving SQLMesh a try and the Athena adapter is something I would definitively love

Thank you in advance!

**Comment by pixie79** [comment]
As someone that builds Greenfield data estates we often start with Athena then switch to other tooling later to manage our data estate when there is volume. It would be great to see Athena supported here like it is with DBT core

**Comment by georgesittas** [comment]
@erindru should we close this given #3154?

**Comment by nicor88** [comment]
@erindru before closing this, I would like to know if:
* partitioned tables are supported
* table properties for iceberg specifically are supported (see [this](https://github.com/TobikoData/sqlmesh/pull/3154#discussion_r1775103036))

If not, those are relevant features that I've see used quite a lot in dbt-athena, and might be relevant to have those features in.

**Comment by erindru** [comment]
With the initial implementation:
- Partitioned Iceberg tables are supported
- Partitioned Hive tables are partially supported. They can be created but operations that need to delete data will currently fail
- Table properties are supported, any `physical_properties` that don't have a special meaning to the adapter are passed through

Follow-up PR's will add:
- Full support for partitioned Hive tables (in so far as emulating the DBT method for incremental models of identifying affected partitions, looking up their location in the metastore, deleting the objects from S3 and then dropping the partition)
- Support for loading `dbt-athena` projects

So @georgesittas this isnt quite finished yet

**Comment by nicor88** [comment]
@erindru Nice, those are the type of features that I was expecting, great work, I will give it a try soon:)

Is the follow up PR WIP? I didn't find anything in the open PR regarding Athena.

**Comment by erindru** [comment]
Yep, still working on it. I'll link to this issue in the next PR when it's raised

**Comment by erindru** [comment]
This is now released in [v0.125.5](https://github.com/TobikoData/sqlmesh/releases/tag/v0.125.5)

The docs are here: https://sqlmesh.readthedocs.io/en/stable/integrations/engines/athena/

Take it for a spin and let us know if you encounter any issues!
