### ISSUE TITLE
Is there a specific version that is required to integrate a redshift dbt project? 

### ISSUE THREAD

**Issue by elijj** [TobikoData/sqlmesh#1318]
I was able to run `sqlmesh init -t dbt` and see the config.py created in my project directory. Although if I try to run `sqlmesh plan` I catch this error:

`ImportError: cannot import name 'RedshiftColumn' from 'dbt.adapters.redshift'`

It looks like [this line](https://github.com/TobikoData/sqlmesh/blob/2fa1454eca94133627a073708e074e211667227e/sqlmesh/dbt/target.py#L362C14-L362C36) is throwing the error.

Is there a specific version of the dbt-redshift adapter I need to use in order to integrate properly? I am currently pinned to [1.6.0](https://github.com/dbt-labs/dbt-redshift/tree/1.6.latest)

**Comment by elijj** [comment]
Looks like it https://github.com/dbt-labs/dbt-redshift/blob/1.6.latest/dbt/adapters/redshift/__init__.py 
ill pin to 1.5.9 
This could be good to include in the docs or notate somewhere
Thanks for the quick reply

**Comment by crericha** [comment]
Our dbt customers are still largely using 1.5 or older, so this was just one of those things we weren't aware of. I'll have a fix in tomorrow.
