### ISSUE TITLE
Add support for Type 2 Dimensions

### ISSUE THREAD

**Issue by eakmanrq** [TobikoData/sqlmesh#134]
Conceptually we want to make it easy for users to define a table as a type 2 dimension and SQLMesh will handle the details of maintaining the additional column(s) and make sure they are accurate from a load pattern perspective. There will likely need to be a discussion on tech design for this prior to starting work.

**Comment by tobymao** [comment]
https://sqlmesh.readthedocs.io/en/stable/concepts/models/model_kinds/#scd-type-2

**Comment by sahmadinejad-varmour** [comment]
hey @tobymao is there any timeline on when scd type 2 models will support other types of columns in the source table?

**Comment by tobymao** [comment]
@eakmanrq

**Comment by eakmanrq** [comment]
@sahmadinejad-varmour What do you mean other types of columns in the source table? Are you talking about how we could check columns for changes instead of relying on an updated_at timestamp?

**Comment by sahmadinejad-varmour** [comment]
yes correct. as described in your docs:

>Limitations
Currently SCD Type 2 requires an update column to be defined on the table you are sourcing your data from. Soon we will also be supporting checking column values in cases where an update column is not available.

**Comment by sahmadinejad-varmour** [comment]
I kinda feel the INCREMENTAL_BY_UNIQUE_KEY model is a better alternative for implementing an SCD type 2 model if I can implement and control valid_from and valid_to column myself.
