### ISSUE TITLE
Access models in python models and macros

### ISSUE THREAD

**Issue by eakmanrq** [TobikoData/sqlmesh#1343]
Currently the way to access a table is by doing `context.table(<table_name>)`. This assumes though that there is a database object that can be referenced like a table or a view. This doesn't work then for `embedded`. We should create a new method to return an expression which could either be a table reference or a subquery which would be the embedded logic. If we do this then we need to update our lineage parsing to support that method and consider what we want to do with `table` (continue to support it or make it private and not part of lineage).

**Comment by tobymao** [comment]
@eakmanrq rename / re-describe this issue as expose models in the evaluation context for python models / macros, 

@z3z1ma wanted this

**Comment by eakmanrq** [comment]
Would we then assume that if a model is accessed then it should be part of the lineage?

**Comment by tobymao** [comment]
no, it shouldn’t be because it could be a metadata only call

**Comment by z3z1ma** [comment]
We should just make available the models that are parents of the current model in the `MacroContext`. Then there is no lineage resolution dependency on this; and it is flexible whether the upstream models are available in the context or not.


80% of the time, you are interested in a direct dependency -- such as getting the column names / column to types of an upstream model which is incredibly useful/powerful... Especially a contracted external model. Very powerful. You can apply renaming rules, if statement checks on column presence, etc etc

cc @eakmanrq / @tobymao
