### ISSUE TITLE
State migration can't run concurrently with plan application

### ISSUE THREAD

**Issue by izeigerman** [TobikoData/sqlmesh#1383]
Right now if someone happens to run the SQLMesh state migration while there is an ongoing plan application, it may lead lead to unexpected results, lost data intervals and even corrupted state altogether. 

This imposes an additional burden on users who are required to carefully orchestrate state migrations and make sure that no other users who work on the same SQLMesh project run a plan application while the migration is ongoing.

We should make sure that it's safe to run a migration while there is an ongoing plan application and vice versa.

**Comment by tobymao** [comment]
cloud only feature
