### ISSUE TITLE
Support for read_csv configuration

### ISSUE THREAD

**Issue by cmvarmour** [TobikoData/sqlmesh#1434]
We have a contract in our data pipeline which relies on a particular CSV format. The downstream consumers of this contract are the area where we are integrating sqlmesh. We want to create a seed model which can consume one of these CSVs, but it doesn't conform to pandas defaults.

We'd love to be able to supply a read_csv configuration object.

Here's an example csv we're wanting to create seed models from

```
start_time,end_time,proto_num,description
'2023-01-27 02:51:08+00','2023-01-27 02:52:08+00',17,'Great stuff bud\'s'
```

**Comment by izeigerman** [comment]
The csv in the description can now be parsed correctly using the following model definition:
```
MODEL (
    name ...,
    kind SEED (
        path '../seeds/test.csv',
        csv_settings (
            quotechar = '''',
            escapechar = '\',
        ),
    ),
    ...
 )
 ```
