### ISSUE TITLE
Clone tables instead of creating blank temporary tables for engines that support it

### ISSUE THREAD

**Issue by izeigerman** [TobikoData/sqlmesh#144]
When iterating in development environment today, the platform creates temporary tables for new snapshots that reuse previous versions to avoid affecting tables that can be used in prod environment.

Temporary tables help ensure isolation but provide a limited preview to a user.  To ensure support for complete previews we can use the table cloning feature available in some engines (eg. [Snowflake](https://docs.snowflake.com/en/user-guide/tables-storage-considerations.html#label-cloning-tables), [Delta Lake](https://docs.snowflake.com/en/user-guide/tables-storage-considerations.html#label-cloning-tables), etc.)

For new snapshots, Instead of creating new temporary tables, we should instead clone the existing tables while updating their schemas to match the schemas of these new snapshots. 

There's still an open question of how to keep clones that fell behind up to date in various development environments.

**Comment by tobymao** [comment]
implemented
