### ISSUE TITLE
Enable pydantic>=2.0 support

### ISSUE THREAD

**Issue by tanghyd** [TobikoData/sqlmesh#1513]
Currently our team is working in an environment which requires `pydantic >= 2.0` and would like to include sqlmesh in its dependencies, but we have a version conflict here.

Looking at recent pull requests, I can see that work has already been merged to support Pydantic 2, see: https://github.com/TobikoData/sqlmesh/pull/1290. However if I inspect the setup.py file I find that there is forced version requirement of `pydantic[email]>=1.10.7,<2.0.0`, which means this support must not be enabled yet.

I did not see a pre-existing open issue on this topic so I made this one to watch progress. Let me know if I've missed something crucial here and if so feel free to close this issue.

**Comment by izeigerman** [comment]
@tanghyd despite the hardcoded `pydantic` support by default, we do support Pydantic 2 with this dependency:
```
pydantic[email]~=2.3.0
```
or below (they broke something in 2.4 as far as I remember). Can you try it?

In the meantime we'll make sure to fix `setup.py`.

**Comment by tanghyd** [comment]
> @tanghyd despite the hardcoded `pydantic` support by default, we do support Pydantic 2 with this dependency:
> 
> ```
> pydantic[email]~=2.3.0
> ```
> 
> or below (they broke something in 2.4 as far as I remember). Can you try it?
> 
> In the meantime we'll make sure to fix `setup.py`.

Very prompt! Thank you very much

**Comment by tanghyd** [comment]
It seems like `sqlmesh ui` fails to run with an fresh virtual environment installed with `sqlmesh==0.37.0` due to `pydantic-settings` not included alongside `pydantic[email]` in the setup.py dependencies, i.e.

    ModuleNotFoundError: No module named 'pydantic_settings'

I imagine the fix should be something like including `pydantic-settings` in the setup.py dependencies (perhaps only as part of `sqlmesh[web]` dependencies), possibly conditional on the pydantic version (as I imagine you don't want to force this if someone is running `pydantic<2.0` (?)).

**Comment by tanghyd** [comment]
It also seems like I am getting the following warning when running `sqlmesh ui` even after installing `pydantic-settings`, namely:

    /home/user/mambaforge/envs/sqlmesh_env/lib/python3.10/site-packages/pydantic/_internal/_fields.py:127: UserWarning: Field "model_name" has conflict with protected namespace "model_".
    
    You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.

So far I can't seem to see if this causes any tangible problems - it seems fine so far.

**Comment by vchan** [comment]
@tanghyd I wanted to let you know we decided to re-pin Pydantic to v1 since v2 is still relatively new. While v1 will be installed by default, you can still use Pydantic v2 with SQLMesh by installing it. We took a look to see if it's possible to configure setuptools to install v2 and pydantic-settings in a separate extras target, e.g. `sqlmesh[web,pydanticv2]`, but couldn't find a solution.
