### ISSUE TITLE
Dynamically Update Pinned Environment Views on Snapshot Unpause

### ISSUE THREAD

**Issue by eakmanrq** [TobikoData/sqlmesh#1543]
Currently if a snapshot is unpaused (applied to prod) then existing environments will continue to point to the temp table despite the fact that the change is now live in production. The goal of this change is to update these existing views to now point to prod instead of the temp table.

One challenge with this is that the number of environments could be N and therefore this could be an expensive operation. Therefore a way to reduce N is to say that we will only updated pinned environments. This gives an extra property to pinned environments that they will be automatically refreshed on changes like this and help support their goal of being long-running environments.

**Comment by tobymao** [comment]
doesn't seem like anyone has asked for this closing
