### ISSUE TITLE
ERROR: Failed building wheel for pyarrow

### ISSUE THREAD

**Issue by cotrariello84** [TobikoData/sqlmesh#1623]
Dear team,
I am trying to install 
`pip install "sqlmesh[web]"`
but I get the error in the topic adding this: RuntimeError: Not supported on 32-bit Windows

Any tips?

Thanks 
Carmine

**Comment by treysp** [comment]
Hello - thanks for reaching out. What version of Windows and Python are you running?

Also, could you run this in Python?
```
>>> import struct
>>> struct.calcsize("P") * 8
```

**Comment by cotrariello84** [comment]
Hi @treysp ,
running this
```
print(platform.platform())
print(platform.system())
print(platform.release())
print(platform.version())
print(platform.version().split('.')[2]) 
print(platform.machine())
```
output:
```
32
Windows-10-10.0.22621-SP0
Windows
10
10.0.22621
22621
AMD64
```


and yes  I can run the above command: 
```
>>> import struct
>>> struct.calcsize("P") * 8
```

**Comment by treysp** [comment]
Thanks! What value does the `struct.calcsize("P") * 8` command return?

**Comment by treysp** [comment]
Also, are you using a virtual environment or a system python install?

**Comment by treysp** [comment]
The core of the problem is that pip is pulling libraries for a 32-bit python version, so you need to make sure you have a 64-bit version of python installed on your machine and that Windows hits it on the PATH.

**Comment by cotrariello84** [comment]
> Thanks! What value does the `struct.calcsize("P") * 8` command return?

return 32

**Comment by cotrariello84** [comment]
> Also, are you using a virtual environment or a system python install?

following the documentation I am using a Virtual Env

**Comment by cotrariello84** [comment]
> The core of the problem is that pip is pulling libraries for a 32-bit python version, so you need to make sure you have a 64-bit version of python installed on your machine and that Windows hits it on the PATH.

Ok, I'll try it

**Comment by cotrariello84** [comment]
Hi @treysp, I installed the right version of python.
But now I get another error message: 
` ERROR: Failed building wheel for duckdb
Successfully built pandas
Failed to build duckdb
ERROR: Could not build wheels for duckdb, which is required to install pyproject.toml-based projects`
