### ISSUE TITLE
Case Sensitive "ModelName" Support for Postgres Engine

### ISSUE THREAD

**Issue by deschman** [TobikoData/sqlmesh#1626]
When using the postgres engine and dialect, if I create two models:

SeedModel.sql
```
MODEL (
    name "SqlmeshExample"."SeedModel",
    kind SEED (
        path '../seeds/seed_data.csv'
    ),
    columns (
        id INTEGER,
        "itemId" INTEGER,
        ds TEXT
    ),
    grain [id, ds]
);
```
IncrementalModel.sql
```
MODEL (
    name "SqlmeshExample"."IncrementalModel",
    kind INCREMENTAL_BY_TIME_RANGE (
        time_column ds
    ),
    start '2020-01-01',
    cron '@daily',
    grain [id, ds]
);

SELECT
    id,
    "itemId",
    ds,
FROM
    "SqlmeshExample"."SeedModel"
WHERE
    ds between @start_ds and @end_ds
```

SQLMesh will create two schemas in my database, `sqlmeshexample` and `SqlmeshExample` where the models `SqlmeshExample.SeedModel` and `sqlmeshexample.incrementalmodel` are created. I would expect these models to be both found under `SqlmeshExample` and be called `SeedModel` and `IncrementalModel`, respecting the double quotes used to define them. 

Attached is the log file while SQLMESH_DEBUG was set to 1, for reference.
[sqlmesh_2023_10_27_14_02_00.log](https://github.com/TobikoData/sqlmesh/files/13192010/sqlmesh_2023_10_27_14_02_00.log)

**Comment by tobymao** [comment]
i was having trouble replicating this. it could be an issue with leftover state in your database, but on a minimal example with a fresh project, sqlmesh was respecting casing.

closing this for now
