### ISSUE TITLE
Error: nvarchar max not handled in mssql EngineAdapter

### ISSUE THREAD

**Issue by JonasDavisFondene** [TobikoData/sqlmesh#1690]
"nvarchar" should be included in the membership check, when handling max length columns, here: https://github.com/TobikoData/sqlmesh/blob/main/sqlmesh/core/engine_adapter/mssql.py#L84

Otherwise create_external_models will make schema.yaml files like:
<pre>
- name: schema_name.table_name
  columns:
    column_name: VARCHAR
</pre>

FULL models selecting such columns from an external model, that do not explicit cast the datatype, will create a sqlmesh__ table with column type VARCHAR(1) causing errors similar to the following when running sqlmesh plan or sqlmesh run:
<pre>
pymssql._pymssql.OperationalError: (2628, b"String or binary data would be truncated in table 'database.sqlmesh__schema_name.table__name__some_number', column 'colum_name'. Truncated value: '4'.DB-Lib error message 20018, 
severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")
</pre>

Proposed fix:
https://github.com/TobikoData/sqlmesh/compare/main...JonasDavisFondene:sqlmesh:patch-1

**Comment by treysp** [comment]
Thanks for the report and patch! Do you want to submit the patch as a PR?

**Comment by tobymao** [comment]
we'll take it, thanks @JonasDavisFondene

**Comment by JonasDavisFondene** [comment]
> Thanks for the report and patch! Do you want to submit the patch as a PR?

I can see from https://sqlmesh.readthedocs.io/en/stable/development/ that I need some prerequisites, I haven't installed yet.

What's the PR process?

**Comment by tobymao** [comment]
it's just the standard pr process, i created a PR with your patch for you here https://github.com/TobikoData/sqlmesh/pull/1691

you just need to sign the cla
