### ISSUE TITLE
[DBT adapter] Config module '.../config.py' was not found

### ISSUE THREAD

**Issue by adrivn** [TobikoData/sqlmesh#1705]
Hello,

Running sqlmesh v0.52 on Windows 10, clean virtual environment.

I copied my current dbt project into a new folder, and ran `sqlmesh init -t dbt` inside the folder, which creates the `config.py` file containing the dbt loader

```python
   1   │ from pathlib import Path
   2   │
   3   │ from sqlmesh.dbt.loader import sqlmesh_config
   4   │
   5   │ config = sqlmesh_config(Path(__file__).parent)
```

However upon running `sqlmesh ui` right after that (within the same folder), the it does not seem to find the config file. Here's the output:

```powershell
└─> sqlmesh ui
Error: Config module 'C:\Users\User\Projects\dbt-sqlmesh\config.py' was not found.
```

I haven't seen anything to this end in the existing issues.

Thanks

**Comment by tobymao** [comment]
This means that something failed during initialization, we'll fix the error message, in the meantime can you run with --debug and share the logs?

sqlmesh --debug ui

**Comment by izeigerman** [comment]
@adrivn I think it's expecting `password`, but the `pass` was provided in the `profiles.yml`.  It looks like it should be `password` according to documentation: https://docs.getdbt.com/docs/core/connect-data-platform/postgres-setup

**Comment by adrivn** [comment]
It does run now. Strange. I ran dbt normally with that config `pass` instead of `password` and didn't throw any error. Guess it might have been deprecated somehow since I first created the project.

I can run the adapter now. Thank you. I'm closing this.
