### ISSUE TITLE
feature request: open lineage integration

### ISSUE THREAD

**Issue by tmnd1991** [TobikoData/sqlmesh#1730]
Is it planned to implement integration with open lineage to make sqlmesh a producer of lineage information like dbt does?

**Comment by tobymao** [comment]
hey @tmnd1991, we don't have plans for this right now, but we'd certainly be open to accept a PR for this. it doesn't look too difficult. additionally this PR could probably be made to openlineage as the dbt, dagster, flink, airflow, and spark integrations are implemented there.

**Comment by wslulciuc** [comment]
@tobymao 👋 I just might be able to help here on the OpenLineage integration :)

What would be a good first step, a proposal?

**Comment by tobymao** [comment]
@wslulciuc join our slack and we can discuss, would be great if you were interested in contributing.
