### ISSUE TITLE
Unable to find `config.py` when importing `CloudComposerSchedulerConfig`

### ISSUE THREAD

**Issue by arabinelli** [TobikoData/sqlmesh#1875]
Hi team, I am building a test project in SQLMesh and I had an issue it took me a while to troubleshoot.

## Issue
When I tried to run the any `sqlmesh` command from cli, I got the following error:
`Error: Config module '/root/workspaces/sqlmesh-project/config.py' was not found.`

I did confirm the file was on the right path.
## Possible cause
As you can see in my `config.py` below, while I was developing I left the `CloudComposerSchedulerConfig` unused import at the top. As soon as I commented it out, sqlmesh could find the `config.py` file and execute.

I further checked and saw that `CloudComposerSchedulerConfig` is missing from `sqlmesh/core/config/__init__.py` (L26). When reintroducing it in my local library, the cli app started to work again as expected.

SQLMesh version is 0.61.0

## Desired behavior
Aside the `CloudComposerSchedulerConfig` import fix, I found the error message to be misleading and a bit hard to debug. 

Something along the lines of the following would improve the experience:
```sh
Invalid config.py file

Traceback (most recent call last):
  File "/root/workspaces/sqlmesh-project/config.py", line 1, in <module>
    from sqlmesh.core.config import (
ImportError: cannot import name 'CloudComposerSchedulerConfig' from 'sqlmesh.core.config' (/usr/local/lib/python3.10/site-packages/sqlmesh/core/config/__init__.py)
```

## Code
This is my `config.py` file:
```python
from sqlmesh.core.config import (
    AirflowSchedulerConfig,
    BigQueryConnectionConfig,
    BuiltInSchedulerConfig,
    CloudComposerSchedulerConfig,
    Config,
    DuckDBConnectionConfig,
    GatewayConfig,
    ModelDefaultsConfig,
)

BIGQUERY_CONNECTION = BigQueryConnectionConfig(
    type="bigquery", method="oauth", project="my-sample-project"
)
DUCKDB_TEST_CONNECTION = DuckDBConnectionConfig(database="test.db")

config = Config(
    gateways={
        "local": GatewayConfig(
            connection=BIGQUERY_CONNECTION,
            state_connection=DuckDBConnectionConfig(database="state.db"),
            test_connection=DUCKDB_TEST_CONNECTION,
            scheduler=BuiltInSchedulerConfig(),
        ),
        "airflow_local": GatewayConfig(
            connection=BIGQUERY_CONNECTION,
            test_connection=DUCKDB_TEST_CONNECTION,
            scheduler=AirflowSchedulerConfig(
                airflow_url="http://airflow-webserver:8080",
                username="airflow",
                password="airflow",
            ),
        ),
    },
    default_gateway="airflow_local",
    model_defaults=ModelDefaultsConfig(dialect="bigquery"),
)
```

**Comment by tobymao** [comment]
this error message is improved with this commit that just landed

https://github.com/TobikoData/sqlmesh/commit/183440ca15f8c0b5f7a29c302cee08ddebf9563b

**Comment by arabinelli** [comment]
@tobymao will also the import be fixed? According to [the docs](https://sqlmesh.readthedocs.io/en/latest/guides/configuration/#cloud-composer) it should work

**Comment by tobymao** [comment]
600ca00b, for now you can just import the full path which is 

from sqlmesh.core.config.scheduler import ...

**Comment by arabinelli** [comment]
Awesome, thanks! 🙏
