### ISSUE TITLE
INCREMENTAL_BY_TIME_RANGE models generate invalid SQL on Trino / Iceberg

### ISSUE THREAD

**Issue by erindru-BitMEX** [TobikoData/sqlmesh#1998]
**Note:** I'm aware that only Hive is officially supported in the SQLMesh Trino connector, i'm just raising this because I think Iceberg is on the todo list so this information might be useful when implementing Iceberg support.

Versions:
- Trino 435 with Iceberg connector pointed at AWS Glue Data Catalog / S3
- sqlmesh 0.68.0

Model:
```
MODEL (
    name landing.model1,
    kind INCREMENTAL_BY_TIME_RANGE (
        time_column timestamp,
    ),
    start '2023-06-01',
    cron '0 * * * *',
);

select id, timestamp
from base_schema.base_table
```

Generated SQL:
```
CREATE TABLE IF NOT EXISTS "catalog"."sqlmesh__landing"."model1__3844959144__temp"
WITH (PARTITIONED_BY=ARRAY['timestamp'])
AS SELECT ..... <rest of query is fine>
```

This produces an error:
`io.trino.spi.TrinoException: Catalog 'catalog' table property 'partitioned_by' does not exist`

The issue is that the table property for partitioning is called `partitioning` in the [Iceberg connector](https://trino.io/docs/current/connector/iceberg.html#partitioned-tables), not `partitioned_by`.

Note that `partitioned_by` is completely valid for a Hive table, so this isnt a bug per se. It's annoying that Trino isn't consistent with its property naming across official connectors.

**Comment by tobymao** [comment]
this is a sqlglot issue cc @georgesittas

**Comment by georgesittas** [comment]
so, depending on the connector, the trino property syntax changes?

**Comment by georgesittas** [comment]
Yeah, we're able to control the generation logic at runtime as well using dialect options so this shouldn't be too much to fix once we understand the scope a bit better.

**Comment by treysp** [comment]
@erindru Did #2129 complete this, or is there remaining work to do?
