### ISSUE TITLE
[Bigquery] add labels property to VIEWs

### ISSUE THREAD

**Issue by treysp** [TobikoData/sqlmesh#2014]
SQLMesh allows a model to pass arbitrary table properties to its `CREATE` statement with the [table_properties](https://sqlmesh.readthedocs.io/en/stable/concepts/models/overview/#table_properties) model configuration parameter. 

Most of the properties this is used for relate to physical storage or partitioning and are only relevant for physical tables. Therefore, the properties are not included in view creation statements.

Bigquery supports the [labels](https://cloud.google.com/bigquery/docs/adding-labels#adding_table_and_view_labels) metadata property, which can be applied to both tables and views. They are similar to tags, but they are key-value pairs rather than strings.

This issue requests that a model's labels property be propagated into its views as well as its physical tables.

**Comment by seblum** [comment]
We are looking into something like this as well. We already had the case that some tables have indeed been labeled in BigQuery after adding `table_properties [ lables=[()] ]`. So, I am not sure whether this has been implemented in some cases already.. However, every change to the table, update, or also within virtual tables removed those labels. 

Would be great to have this implemented in general!

**Comment by izeigerman** [comment]
#2517 introduced propagation of `table_properties` into VIEWS in the **physical** layer. We still don't set them in the virtual layer and it's not quite clear whether we even should.

**Comment by plaflamme** [comment]
@izeigerman agreed, it's unclear to me that these should be forwarded since `table_properties` is definitely about the physical layer.

That being said, having the ability to specify labels on the virtual environment views in BigQuery would be nice for integration with other GCP tooling. Having an equivalent `view_properties` for the "virtual layer" would solve this.
