### ISSUE TITLE
Sushi Example doesn't work on Databricks due to Space

### ISSUE THREAD

**Issue by eakmanrq** [TobikoData/sqlmesh#2026]
https://github.com/TobikoData/sqlmesh/blob/bdd2074c606208d2268e9eae7dd81a9cf943ef23/examples/sushi/models/customer_revenue_by_day.sql#L32

```
databricks.sql.exc.ServerOperationError: Found invalid character(s) among ' ,;{}()\n\t=' in the column names of your schema. Please use other characters and try again.
```

**Comment by tobymao** [comment]
@eakmanrq i think we can have spaces if we make databricks use 

delta.columnMapping.mode

https://docs.delta.io/latest/delta-column-mapping.html

do you know how to add this for databricks in the tests?

**Comment by eakmanrq** [comment]
It looks like this is a table property: https://docs.delta.io/latest/delta-column-mapping.html

So we would want to add this to the model table properties I think.
