### ISSUE TITLE
Enable runs and audit slack notifications

### ISSUE THREAD

**Issue by arabinelli** [TobikoData/sqlmesh#2061]
As discussed with @izeigerman via Slack, currently Slack notifications only support plans, but not runs and possibly audits. It would be good to be able to receive notifications for those events as well. 

In addition, as a feature suggestion, it might be desirable in future releases to filter the notification target by model tags in order to reduce alerting fatigue for larger teams. 

E.g. I imagine being able to configure something like
```python
notification_targets=[
    # plans are sent to a specific channels regardless of tags
    SlackApiNotificationTarget(
        notify_on=PLAN_EVENTS,
        token=os.getenv("SLACK_API_TOKEN"),
        channel="UXXXXXXXXX",  # Channel ID of #data-sqlmesh-deploys-prd
    ),
   # runs and audit failures for the marketing team's models
    SlackApiNotificationTarget(
        notify_on=RUN_AND_AUDIT_FAIL_EVENTS,
        token=os.getenv("SLACK_API_TOKEN"),
        channel="UXXXXXXXXX",  # Channel ID of #data-marketing-alerts-prd
        include_tags=["team:marketing"]
    ),
   # runs and audit failures for the data platform team's models
    SlackApiNotificationTarget(
        notify_on=RUN_AND_AUDIT_FAIL_EVENTS,
        token=os.getenv("SLACK_API_TOKEN"),
        channel="UXXXXXXXXX",  # Channel ID of #data-platform-alerts-prd
        include_tags=["team:data_platform"]
    )
]
```
Where `team:data_platform` and `team:marketing` are tags applied in the models DDL

**Comment by petrikoro** [comment]
Hi! Is there any progress on this? We would benefit greatly from this feature

**Comment by tobymao** [comment]
this is available in tobiko cloud, closing this
