### ISSUE TITLE
Schema inferrence fails for `ARRAY<STRUCT<...>>`

### ISSUE THREAD

**Issue by plaflamme** [TobikoData/sqlmesh#2152]
Schema for derived tables and views is typically derived from the source columns. Assuming this base table:

```sql
SELECT '2024-02-01'::DATE AS event_date, 'foo'::STRING AS foo, 42::INT AS bar
```

Then a statement like

```sql
select event_date, foo, bar
```

will correctly infer types for all 3 columns.

This also works for something like this:

```sql
select event_date, STRUCT(foo, bar) AS my_struct
```

meaning that the `STRUCT`'s type will be inferred to `STRUCT<foo STRING, bar INT>`

But currently, this fails when wrapping the struct in an array, e.g.:

```sql
select event_date, ARRAY(STRUCT(foo, bar)) AS my_structs
```

This infers the type to `ARRAY<STRUCT>` which is invalid.

[This commit](https://github.com/plaflamme/sqlmesh/commit/a4bcf7c5934b2dfb9efb1d57d049b14da6895b06) adds an example to reproduce the error and [this commit](https://github.com/plaflamme/sqlmesh/commit/eb9a875643339a372abdec92b7fff950e358fe4a) adds the necessary type cast to fix the problem.

In reality, my actual models look like this:

```sql
model(
  name base_model
);
SELECT event_date, foo, bar
FROM ...
```

And the model where this problem occurs looks something like this

```sql
model(
  name array_agg_model
);
SELECT event_date, ARRAY_AGG(STRUCT(foo,bar)) AS my_structs
FROM base_model
GROUP BY 1
```

The generated BigQuery sql to create the table uses `my_structs ARRAY<STRUCT>` in the statement.

**Comment by tobymao** [comment]
as a temporary workaround, you can do an explicit cast

**Comment by georgesittas** [comment]
I'll take a look, thanks for the report @plaflamme
