### ISSUE TITLE
Add Databricks Serverless SQL Warehouse Support

### ISSUE THREAD

**Issue by eakmanrq** [TobikoData/sqlmesh#2169]
The one known issue is inability to do insert/overwrite on SQL Warehouse: https://community.databricks.com/t5/data-engineering/configuration-spark-sql-sources-partitionoverwritemode-is-not/td-p/43646

We may have to detect a SQL Warehouse connection and then have it do a delete/insert instead. 

We should add a new test to our engine `test_integrations` tests to test both general purpose clusters and Serverless SQL Warehouse.

**Comment by tobymao** [comment]
this is now implement i believe? @eakmanrq

**Comment by eakmanrq** [comment]
Although we don't test it, we do believe this addressed now. Thanks.
