### ISSUE TITLE
Latest dbt version compatibility

### ISSUE THREAD

**Issue by chrishiste** [TobikoData/sqlmesh#2210]
Hey! Just wondering if you're thinking about supporting newer dbt-core versions anytime soon? Right now, it's stuck at <1.5.0. Really keen to try sqlmesh on my own to see how it can make my work easier before I fully switch over.

**Comment by crericha** [comment]
Sure thing!

**Comment by crericha** [comment]
Confirmed SQLMesh works with dbt-core 1.7.9. Created a PR to update the dependency.

**Comment by chrishiste** [comment]
Wow that's fast :) how about `<2.0` instead. It will prevent keeping up to date. I would rather open an issue here because of a breaking change introduced in dbt-core than to request for an upgrade
