### ISSUE TITLE
Add Oracle Execution engines 

### ISSUE THREAD

**Issue by HongQuanVu** [TobikoData/sqlmesh#2236]
Dear SQLMesh team,

Because Oracle database is common used in enterprise environment, especially banking and financial services industry, 

Please help to support Oracle Execution engines.

https://sqlmesh.readthedocs.io/en/stable/integrations/overview/

Regards,
Quan Vu.

**Comment by tobymao** [comment]
we’re happy to partner with a company interested in oracle but for now have received no demand for it so it is not on the road map.

**Comment by nrsmac** [comment]
This would really open up avenues especially with the announcement of multi-engine workflows! Please consider reopening.

**Comment by tobymao** [comment]
If you're interested in sponsoring an Oracle implementation, hit me up on Slack and we can discuss.
