### ISSUE TITLE
[dbt integration] Impossible to cluster on `connectionId` field (reserved field name?!)

### ISSUE THREAD

**Issue by github-christophe-oudar** [TobikoData/sqlmesh#2293]
Using latest build (0.78.dev8), I ran into following error:

If creating a `my_model.sql` with following content:
```
{{
    config(
        materialized='table',
        cluster_by = ["connectionId"],
    )
}}

SELECT 1 as connectionId
```

It fails with:
```
sqlmesh.utils.errors.ConfigError: clustered_by keys ['connectionId'] are missing in the model definition at 'my_model.sql'
```

As it should obviously works it looks like there's something with `connectionId` value that doesn't work for some reason.

**Comment by tobymao** [comment]
by quoting it you’ve made it case sensitive so you need to quote your projection with the same case

**Comment by tobymao** [comment]
i guess this is a dbt project so we should match the behavior. @crericha / @treysp can you make sure we normalize cluster_by for dbt?

**Comment by github-christophe-oudar** [comment]
@tobymao 
> by quoting it you’ve made it case sensitive so you need to quote your projection with the same case
Ok if I use `SELECT 1 as "connectionId"` it works.
Yet you're right, dbt project support the appropriate casing so I'm not sure how it changes within sqlmesh but it could be nice to support it 👍
