### ISSUE TITLE
Support "external signals" for built-in scheduler

### ISSUE THREAD

**Issue by plaflamme** [TobikoData/sqlmesh#2297]
Currently, sqlmesh supports synchronizing with externally scheduled dependencies in the Airflow scheduler via "[external signals](https://sqlmesh.readthedocs.io/en/latest/integrations/airflow/#external-signals)". That is, one can define an "external signal" on a sqlmesh model which allows Airflow to add a node to the DAG to represent a dependency between that model and some external state.

This issue is about extending this capability to the "built-in scheduler" as well: allowing the declaration of external dependencies which are evaluated by the build-in scheduler to determine if a model is "ready" to be evaluated within a `sqlmesh run`.

A public abstraction similar to `BaseSensorOperator` could be defined by sqlmesh, and implemented by sqlmesh users. A "factory method" (equivalent to `create_external_sensor` in the Airflow scheduler) could be provided to the build-in scheduler at config time (i.e.: in `config.py`)

**Comment by tobymao** [comment]
#2822
