### ISSUE TITLE
Enhance SQLMesh to Support Audits for External Sources

### ISSUE THREAD

**Issue by harshvardhan-j** [TobikoData/sqlmesh#2392]
Description:
Currently, SQLMesh supports external sources but lacks the functionality to perform audits on them. The `schema.yaml file` for external models does not include an interface for adding audits, limiting the ability to ensure data integrity and reliability for downstream tables.

Objective:
Implement a feature within SQLMesh to enable audits for external sources, allowing users to verify that downstream tables receive the expected data from these external models.

Context: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1712156303563069?thread_ts=1712149507.981779&cid=C044BRE5W4S

**Comment by tobymao** [comment]
implement by https://github.com/TobikoData/sqlmesh/pull/2715
