### ISSUE TITLE
cannot use hooks in seed model, errors with "not hydrated"

### ISSUE THREAD

**Issue by markgraphene** [TobikoData/sqlmesh#2438]
Would like to create indexes on a seed model, see title.

**Comment by markgraphene** [comment]
actually the "not hydrated" error appears to occur not just by attempting to add hooks, but also by changing the data in the csv.

**Comment by izeigerman** [comment]
@markgraphene this is a known issue that we had in the past. To mitigate this, apply the plan with the --no-diff command when changing that seed model:
```
sqlmesh plan --no-diff <env> 
```
You may need to do just once after you change every existing seed model. 

To fix this for all seed models at once, add a `stamp` attribute with an arbitrary string value to all seed model definitions:
```
MODEL (
    ...
    stamp 'fix hydration issue'
)
```
and then run:
```
sqlmesh plan --no-diff <env> 
```
for all of them.
