### ISSUE TITLE
Brownfield Migration

### ISSUE THREAD

**Issue by dbrtly** [TobikoData/sqlmesh#2471]
My employer has a gcp project with many large bigquery tables. It's one of the factors that prompts the interest in sql runner alternatives. 

An objection to using sqlmesh is "but we would have to rebuild every table in the warehouse with the fingerprints and that's expensive". Is there an existing workaround for this? Example: A rename_tables app that refactors the existing structures to match sqlmesh's user views on table snapshots pattern. 

Are the hashes deterministic and thus could be determined in a separate database and then injected into a rename_tables app? Could this rename_tables app be a plugin to sqlmesh?

**Comment by treysp** [comment]
We recently added a [guide to table migration](https://sqlmesh.readthedocs.io/en/latest/guides/table_migration/) - would either of those methods work for your use case?

More generally, the [fingerprints](https://sqlmesh.readthedocs.io/en/latest/concepts/architecture/snapshots/) are based on the project content/structure, not the data values themselves.
