### ISSUE TITLE
Dagster integration on the way?

### ISSUE THREAD

**Issue by ryandelano** [TobikoData/sqlmesh#2530]
Would rather use dagster than airflow, but also would rather use SQLMesh over dbt. Having a dagster integration would solve this problem well! Has anyone gotten started/would anyone like to get started on getting the dagster integration up and running? Can take this on, but didn't know if it was already in the works.

**Comment by marcounternaehrer-cf** [comment]
Is there any update regarding dagster? I would love to work with SQLMesh

**Comment by tobymao** [comment]
it’s being tested now. it should launch sometime in q1

**Comment by marcounternaehrer-cf** [comment]
That's great news, thank you! I'm really looking forward to this integration :)

**Comment by tevariou** [comment]
Any news on this ?

**Comment by erindru** [comment]
Dagster integration is part of [Tobikio Cloud](https://sqlmesh.readthedocs.io/en/stable/cloud/features/scheduler/dagster/)

**Comment by benelot** [comment]
> it’s being tested now. it should launch sometime in q1

@tobymao We are interested to use sqlmesh, even as a paying customer, but we can only run things on-premise. Is there an option to get the dagster integration for our on-prem dagster with sqlmesh?
