### ISSUE TITLE
Use Python dict instead of a Pydantic model type to set a kind for Python models

### ISSUE THREAD

**Issue by izeigerman** [TobikoData/sqlmesh#2540]
By allowing users to specify model kind as a Pydantic model we give up a certain amount of control over how certain kind fields are being set (eg. `dialect`). As a result we sometimes have to resort to ghastly workarounds to set these values after the fact.

Instead of letting user create the kind instance directly, we should only let them set the kind's settings as a Python dict, so that the actual instance construction can happen downstream where SQLMesh controls the construction process.

Therefore, a typical Python model definition that looks like this:
```
@model(
    kind=IncrementalByTimeRangeKind(time_column="ds", batch_size=10),
    ...,
)
```
should look like this:
```
@model(
    kind=dict(name=ModelKindName.INCREMENTAL_BY_TIME_RANGE, time_column="ds", batch_size=10),
    ...,
)
```

Code examples in docs should be updated accordingly.

**Comment by tobymao** [comment]
cc @treysp
