### ISSUE TITLE
Fix support for multiple repos

### ISSUE THREAD

**Issue by mpcarter** [TobikoData/sqlmesh#2549]
Referring to the multi-repo support described in the docs at https://sqlmesh.readthedocs.io/en/stable/guides/multi_repo/, it does not appear that in v0.92.1 it handles multiple repos the same way.

Similar to the example, I had a repo_1 and a repo_2 where I had one model in repo_2 that was a child, call it `child`, of a model in repo_1, call it `parent`.
repo_2 also had some other models that were not dependent on repo_1. Call one of them `other`.
I bootstrapped using `sqlmesh -p .\repo_1 -p .\repo_2 plan` and all the models generated/backfilled correctly in prod
Next I made a small breaking change to `parent` in repo_1.

Then I ran `sqlmesh -p .\repo_1 plan` . According to the docs, sqlmesh should detect the indirectly modified `child` from repo_2. But instead it just says that `parent` had a breaking change and that `child` and `other` had been removed. Continuing to apply the plan resulted in their removal.
If I redo the experiment but instead run `sqlmesh -p .\repo_1 -p .\repo_2 plan` then it correctly identifies the indirectly modified `child` and updates it (and does not remove `other`)

I also ran another experiment with the same initial setup. Instead of modifying `parent` I changed `child`.
Then ran `sqlmesh -p .\repo_2 plan` . It threw an error along the lines of

> Error: Removed '"MY_DB"."repo_1"."parent"' are referenced in '"MY_DB"."repo_2"."child"'. Please remove broken references before proceeding.

**Comment by tobymao** [comment]
i'm unable to replicate this. i'm going to close this for now but i basically followed the multi-repo guide and got expected results even when working on only one project.

i'll certainly reopen this if i can get a reproducible example.

are both of your repositories compatible in configurations? like dialects?

**Comment by mpcarter** [comment]
I later realized my folly. I was not aware that a `project` key needed to be added to the respective configs for each repo. Once I added that it worked perfectly. Outstanding work BTW! 

I don't think the existing docs make this critical component very obvious unless someone reviews the example in great detail. This configuration option is not even listed on the [configuration reference page](https://sqlmesh.readthedocs.io/en/stable/reference/configuration/#root-configurations) (that I could find anyway).

I have a humble PR here that updates the docs to add this bit of important information
https://github.com/TobikoData/sqlmesh/pull/2552
