### ISSUE TITLE
SQLMesh format converts SAFE_CAST to CAST

### ISSUE THREAD

**Issue by z3z1ma** [TobikoData/sqlmesh#2554]
This is not semantically the same operation. The issue will need to be resolved in sqlglot I imagine but posting here because of its relevance in SQLMesh given the format CLI command.

![image](https://github.com/TobikoData/sqlmesh/assets/41213451/7e1e61a4-edeb-4416-bf69-c913a4a7f655)

**Comment by tobymao** [comment]
@z3z1ma can you share the commands you used for this? i'm not seeing this behavior on sqlglot

```from sqlglot import parse_one

q = parse_one("""
safe_cast(x as int64)
""", read="bigquery")


print(q.sql(dialect="bigquery", pretty=True))

```

**Comment by georgesittas** [comment]
I'll fix this
