### ISSUE TITLE
"Expecting )" error when using named args `@STAR(tbl, except := [col])`

### ISSUE THREAD

**Issue by anentropic** [TobikoData/sqlmesh#2599]
https://sqlmesh.readthedocs.io/en/stable/concepts/macros/sqlmesh_macros/#star

> For example, we might omit the alias argument with `@STAR(foo, except := [c])`

But I get an error:
```
Error: Failed to parse a model definition at '/Users/anentropic/dev/etl/models/orders.sql': Expecting ). Line 51, Col: 28.
  _TRG_USERACCESS_D
        )
    order by W_INSERT_DATE, ORDER_WID
)
select
    @STAR(ranked_orders, except := [row_num])
from ranked_orders
where
    row_num = 1
    and snowflake_last_ingested_at between @.
```

omitting the `except := [row_num]` allows the plan to work

I'm on sqlmesh 0.95.1 and if I look at the files in my virtualenv I appear to have the changes from this PR https://github.com/TobikoData/sqlmesh/issues/2484

**Comment by z3z1ma** [comment]
If the keyword name shadows a sql keyword, you'll likely need to quote it. So `"except" := [c]`

**Comment by georgesittas** [comment]
This needs to be `except_`, it seems like there's a typo in the docs.

**Comment by anentropic** [comment]
then I get:
```
TypeError: star() got multiple values for argument 'except_'
```

from this code:
```sql
select
    @STAR(ranked_orders, except_ := [row_num])
from ranked_orders
where row_num = 1
```

**Comment by georgesittas** [comment]
gotcha thanks, will take a look 👍
