### ISSUE TITLE
Is it possible to implement a custom engine adapter?

### ISSUE THREAD

**Issue by neverchanje** [TobikoData/sqlmesh#2618]
Hey there,
I am new to this innovative data tool and the wonderful community! I saw there are a few built-in engine adapters already and I'd love to contribute the support for [RisingWave](https://github.com/risingwavelabs/risingwave). I wonder if there's any guide for me to start with?

I also notice that there was request for supporting clickhouse: https://github.com/TobikoData/sqlmesh/issues/1300
I believe a wide ecosystem would be crucial for a dataops tool. It'd be nice if you can provide an adapter framework like https://docs.getdbt.com/docs/contribute-core-adapters.

**Comment by tobymao** [comment]
hey @neverchanje, as of right now, we'd be happy to accept a PR for risingwave. 

here's an example of trino being added

the main things you need to add are a new engine adapter, a config, tests, and docs.

https://github.com/TobikoData/sqlmesh/pull/1579/files

as of right now, most of the contributions are core and we are very quick to accept and review PRs. so for now i'm going to close this issue.

i believe it's probably possible to make a Python package that adds a custom adapter, but i'm not sure it makes sense for us to prioritize that at the moment.

but as I said, we would love for you to contribute a rising wave PR and are happy to help you get it in. join us on tobikodata.com/slack for any questions!
