### ISSUE TITLE
BigQuery-Adapter: no overview about "bytes_processed" and "bytes_billed" in the log files -> missing cost overview

### ISSUE THREAD

**Issue by matthias-fbi** [TobikoData/sqlmesh#2626]
When running 
`sqlmesh plan`
or
`sqlmesh run`
I would expect a detailled overview about the executed queries and the
`bytes_processed: x` and `bytes_billed: y`
overview for each executed query (including everything, e.g. the __temp stuff from incremental models) so that I can review which model caused how much costs and then a summed up
`total_bytes_billed: z`
to see the total cost of the project run.

**Comment by tobymao** [comment]
thanks for your issue @matthias-fbi. our enterprise/cloud offering logs this data and displays it for you in our [observer platform](https://sqlmesh.readthedocs.io/en/stable/guides/observer/).

so we don't have plans to implement this in open source.
