### ISSUE TITLE
Start Date Field - Non-numerical symbols

### ISSUE THREAD

**Issue by alinamykal** [TobikoData/sqlmesh#2642]
**Description:**

User can enter non-numerical characters to `Start Date Field`.

**Steps to Reproduce:**

1. User clicks `Plan Button `, `New Page `is opened.
2. User enter non-numerical characters to the `Start Date Field.`

**Actual Result:**
User can enter non-numerical symbols to `Start Date Field.`

Expected Result:
User is unable to enter non-numerical symbols to `Start Date Field.`

**Environment**:
Chrome

Severity:

Version:

![Image](https://github.com/TobikoData/sqlmesh/assets/169292573/de0762d1-90e9-480c-b911-493cfe59fefd)

**Comment by tobymao** [comment]
this is not a bug, we accept things like jan .
