### ISSUE TITLE
Support per-gateway external models

### ISSUE THREAD

**Issue by erindru** [TobikoData/sqlmesh#2689]
Right now, if you have a model that depends on a dynamically named external model, it's hard to `sqlmesh plan` across gateways.

In this scenario, each gateway represents a different _application_ environment. The model structure is the same for each gateway but the naming and actual data is gateway-specific.

For example, consider a model defined like so:
```
MODEL (
   name @{gateway}_landing.my_model
);

select * from @{gateway}_app.source_table;
```

When you run `sqlmesh --gateway dev create_external_models`, this will create an entry in `schema.yml` for `dev_app.source_table`, eg:

```
- name: '"datalake"."dev_app"."source_table"'
  columns: ...
```

However, running for another gateway, eg `sqlmesh --gateway prod create_external_models` just clobbers the existing entry:
```
- name: '"datalake"."prod_app"."source_table"'
  columns: ...
```

Which means you cant run `sqlmesh --gateway dev plan` anymore without re-creating the external models. And the second you do that, cant run `sqlmesh --gateway prod plan` because the external models are now all the dev models.

You end up with warnings like:
```
WARNING - SELECT * cannot be expanded due to missing schema(s) for model(s). Run `sqlmesh create_external_models`
```
and errors like:
```
Error: Removed '"datalake"."prod_app"."source_table"' are referenced in '"datalake"."prod_landing"."my_model"'. Please remove broken references before proceeding.
```

I can see a few options here:
- Put the dynamism in `schema.yml` and resolve it on load. Eg persist the model as `- name: '"datalake"."@{gateway}_app"."source_table"'` and then resolve `@{gateway}` when it's loaded so the downstream code doesn't need to change
- Add a `gateway: ` key on writing the external models and then filter based on it when reading them back. Omitting the `gateway: ` key would mean that the external model gets loaded for all gateways. Something like:
- ```
  - name: '"datalake"."prod_app"."source_table"'
    gateway: prod
    columns: ...
  ```
- Take the opportunity to, instead of using a global `schema.yml` in the root dir, when someone runs `sqlmesh create_external_models`, write the result to `external_models/<gateway>.yml`. The external model loader could still load all of them, but perhaps a post-processing step could be done to prune the list of external models down to just the ones that are referenced in the current `sqlmesh plan` (which would be gateway-specific)

Thoughts?

**Comment by georgesittas** [comment]
@erindru I assume we can close this now right?

**Comment by erindru** [comment]
Yep, although I was waiting for it to be part of a release so I could say which release it was in before closing
