### ISSUE TITLE
Columns typed within CTEs fail to help type inferrence

### ISSUE THREAD

**Issue by plaflamme** [TobikoData/sqlmesh#2709]
Probably a sqlglot limitation, but the following model fails to infer the type of `col`:

```sql
model(name catalog.schema.model);
with base AS(
    select bar::STRING AS col from some_model AS m
)
select col from base
```

Screenshot of the UI:
<img width="881" alt="Screenshot 2024-05-30 at 15 49 19" src="https://github.com/TobikoData/sqlmesh/assets/484152/b4726b58-1b5d-4210-ba2c-18ea7f06371a">

The `::STRING` within the CTE should be sufficient to infer the type of the resulting column even if `some_model` is unknown, for example, this works:

```sql
model(name catalog.schema.model);
select bar::STRING AS col from some_model AS m
```

**Comment by tobymao** [comment]
this is expected because sqlmesh is very conservative with annotations. if your model schema is know fully known (you need to use external models), then we don't infer the schema for you. 

the reason for this is that the qualification step can have some ambiguities in it that are impossible to get right with having full knowledge of the schema.

so if you have external models, the type annotations should work.

**Comment by plaflamme** [comment]
> so if you have external models, the type annotations should work.

Well, in our actual use-case, the column I was hoping to get typed is derived from another one, the actual model is something like this:

```sql
with base as(
  SELECT JSON_VALUE(h.some_json, '$.foo')::STRING AS col FROM ...
)
SELECT col FROM base
```

So I don't think the external schema will help here.

> another workaround and something that we consider "sqlmesh best practice" is to directly annotate the final projections of your query.

This is what we've been doing, but it gets a bit cumbersome from complicated columns, we have models that look like this:

```sql
select ARRAY(
  select as struct
    many, columns, go, here, each, with, an, explicit, cast::STRING FROM ...
) FROM ...
```

These `::ARRAY<...>` casts in the final model get pretty cumbersome to maintain. I was hoping that sqlmesh could infer the type for situations where the casting is done explicitly elsewhere.

**Comment by tobymao** [comment]
@plaflamme i believe this should work as long as all the sources have a schema or are annotated.

so if the FROM ... is known, then the STRING will get propagated
