### ISSUE TITLE
How to add comments to columns using a Python model

### ISSUE THREAD

**Issue by zerodarkzone** [TobikoData/sqlmesh#2710]
Hi,
When creating a sql model you can add comments to every column and it will get registered in the table and view schemas.
Is it possible to do the same when creating a Python model?

I'm using pyspark

**Comment by treysp** [comment]
Hello - this is now possible by passing a `column_descriptions` dict to the python model `@model()` decorator. 

This docs example model includes column descriptions:

```
import typing as t
from datetime import datetime

import pandas as pd
from sqlmesh import ExecutionContext, model

@model(
    "docs_example.basic",
    owner="janet",
    cron="@daily",
    columns={
        "id": "int",
        "name": "text",
    },
    column_descriptions={
        "id": "Unique ID",
        "name": "Name corresponding to the ID"
    },
)
def execute(
    context: ExecutionContext,
    start: datetime,
    end: datetime,
    execution_time: datetime,
    **kwargs: t.Any,
) -> pd.DataFrame:

    return pd.DataFrame([
        {"id": 1, "name": "name"}
    ])
```

Docs link is to the "latest" version, so you will see a warning banner. Content will appear in the "stable" version once a new SQLMesh release occurs.

https://sqlmesh.readthedocs.io/en/latest/concepts/models/python_models/#basic

**Comment by zerodarkzone** [comment]
Hi, 
I'm having problems using this feature on databricks.

``` python
@model(
    name="raw.ps_mcortes",
    kind="FULL",
    cron="@daily",
    grain="MCR_CVE_N",
    description="Tabla con informacion sobre tipos de corte",
    columns={
        "MCR_CVE_N": "BIGINT",
        "MCR_DESC_STR": "STRING",
        "MCR_TIPO_STR": "STRING",
        "MCR_EST_STR": "STRING",
    },
    column_descriptions_={
        "MCR_CVE_N": "Clave de material de corte",
        "MCR_DESC_STR": "Descripción del corte",
        "MCR_TIPO_STR": "Tipo de material de corte",
        "MCR_EST_STR": "Estatus del tipo de material de corte",
    },
)
```
I have this model definition. When I try to do a sqlmesh plan or migrate, I'm getting the following error:
`sqlmesh.utils.errors.ConfigError: In model 'raw.ps_mcortes', a description is provided for column 'MCR_CVE_N' but it is not a column in the model.`

I think is because of the case of the columns.
I've prnted the values of the columns and the descriptions and this is what I get:

```
2024-06-04 11:50:23,146 - MainThread - sqlmesh.core.model.meta - ERROR - {'mcr_cve_n': DataType(this=Type.BIGINT, nested=False), 'mcr_desc_str': DataType(this=Type.TEXT, nested=False), 'mcr_tipo_str': DataType(this=Type.TEXT, nested=False), 'mcr_est_str': DataType(this=Type.TEXT, nested=False)} (meta.py:236)
2024-06-04 11:50:23,146 - MainThread - sqlmesh.core.model.meta - ERROR - {'MCR_CVE_N': 'Clave de material de corte', 'MCR_DESC_STR': 'Descripción del corte', 'MCR_TIPO_STR': 'Tipo de material de corte', 'MCR_EST_STR': 'Estatus del tipo de material de corte'} (meta.py:237)
```

It looks like the column type mapppings are in lowercase and the column_descriptions are in uppercase so it fails. It doesn't matter if I change the keys of the descriptions to be lowercase.
