### ISSUE TITLE
Problem with SCD Type 2 models

### ISSUE THREAD

**Issue by zerodarkzone** [TobikoData/sqlmesh#2764]
Hi,
I'm using sqlmesh version 0.102.1 and Databricks.

We have an SCD Type 2 model defined in the following way:
``` SQL
MODEL (
  name silver.articulos_curado,
  kind SCD_TYPE_2_BY_COLUMN (
    unique_key id_articulo,
    columns ARRAY(
      estatus_articulo,
      descripcion,
      clave_tipo_articulo,
      clave_marca_proveedor,
      clave_acabado,
      clave_marca_price
    ),
    on_destructive_change allow
  ),
  cron '@daily',
  grain sid,
  description 'Todos los elementos de la tabla articulo, es decir, todos los productos que maneja la empresa'
);

SELECT
  UUID() AS sid, /* Unique ID */
  ID_ART AS id_articulo, /* Identificador del articulo */
  AR_ESTATUS_STR AS estatus_articulo, /* Estatus del articulo */
  AR_DESC_STR AS descripcion, /* Descripcion del articulo */
  TAR_CVE_N AS clave_tipo_articulo, /* Clave del tipo de articulo ( calzado, accesorio, ropa o folletos) */
  MAR_CVE_N AS clave_marca_proveedor, /* Clave de la marca del articulo */
  ACA_CVE_N AS clave_acabado, /* Clave del acabado del articulo */
  MP_CVE_N AS clave_marca_price /* Clave de la marca price */
FROM raw.articulo;
```

Whenever we try to change a column name or add a new column, even if the command `sqlmesh plan` finishes without problems. We are not seeing the changes on Databricks so no column gets added or renamed.

When we try to restate the model running `sqlmesh plan dev_juan --restate-model "silver.articulos_curado"` we get an error saying that the previous column name does not exists.

``` 
databricks.sql.exc.ServerOperationError: [UNRESOLVED_COLUMN.WITH_SUGGESTION] A column, variable, or function parameter with name `marca_price_shoes` cannot be resolved. Did you    
mean one of the following? [`clave_marca_price`, `id_articulo`, `clave_acabado`, `clave_division`, `clave_horma`]. SQLSTATE: 42703; line 1 pos 1000

```
For now, the only "fix" has been to change de model name to a temporal one (ex: articulos_temp), run the plan and change the name again so sqlmesh recreates the schema.

Is there a way to force sqlmesh to recreate a model from scratch?

**Comment by izeigerman** [comment]
In order to preview changes for SCD 2 and other forward-only models, you need to enable data previews, or in other words, run the plan command with the `--enable-preview` flag, or set it in the config:
```
plan:
    enable_preview: true
```

Not sure what `marca_price_shoes` refers to since I can see it in the model definition.

**Comment by zerodarkzone** [comment]
Hi, 
Could you exlain what does enable-preview does?

I don't know if I explained the problem correctly.

Basically, sqlmesh plan is not updating the schema of the SCD Type 2 models and the backfill fails when trying to do a restatement. 
Is that the expected behaviour?
