### ISSUE TITLE
compiled query incorrect when using EXISTS clause (TSQL)

### ISSUE THREAD

**Issue by sinia** [TobikoData/sqlmesh#2765]
When using EXISTS clause in a model (TSQL dialect MSSQL connection), I get incorrectly compiled SQL query, fails to execute on MSSQL server.

Model source code:
```sql
MODEL (
  name myschema.mymodel,
  kind VIEW
);

select 1 where exists (select 1)
```

Resulting compiled query:
```sql
SELECT
  1 AS [1]
WHERE
  EXISTS(
    SELECT
      1 AS [1]
  ) <> 0
```

Note appended ` <> 0` to the compiled code, this results in failed execution on MSSQL server.

I am using the following on windows (Python 3.11.5):
sqlglot==25.0.3
sqlmesh==0.104.0

**Comment by georgesittas** [comment]
Fixed in https://github.com/tobymao/sqlglot/commit/1afe6ac62b9c827a001c5a6ab917304c5756fb09
