### ISSUE TITLE
MSSQL Common language runtime (CLR) types get wrongly parsed

### ISSUE THREAD

**Issue by elauser** [TobikoData/sqlmesh#2817]
I want to use the geography clr type from mssql https://learn.microsoft.com/en-us/sql/t-sql/spatial-geography/spatial-types-geography?view=sql-server-ver16

But it interprets the :: as a cast and turns 

GEOGRAPHY::Point([latitude], [longitude], 4326) AS geopoint_new,
into 
CAST([GEOGRAPHY] AS Point(LATITUDE, LONGITUDE, 4326)) AS [geopoint_new],

I'm using that to get the geospatial distance between two points. Otherwise I have to roll up my own geospatial calculation in sql.

**Comment by georgesittas** [comment]
cc @VaggelisD
