### ISSUE TITLE
SAFE_CAST DATE compiles to PARSE_DATE

### ISSUE THREAD

**Issue by hustic** [TobikoData/sqlmesh#2827]
This is probably related to SQLGlot. Can raise it there if it's more appropriate.

Dialect: BigQuery

I am dealing with a column that contains different formatted DATEs. I wanted to use COALESCE to string together SAFE_CASTs with different DATE FORMATs.

```sql
COALESCE(
  SAFE_CAST(sampling_date AS DATE FORMAT 'DD MONTH YYYY'),
  SAFE_CAST(sampling_date AS DATE FORMAT 'DD-MONTH-YYYY')
) AS sampling_date,
```

However, this gets compiled into:

```sql
COALESCE(
    PARSE_DATE('%d %B %Y', `raw_sims_checkin`.`sampling_date`),
    PARSE_DATE('%d-%B-%Y', `raw_sims_checkin`.`sampling_date`)
  ) AS `sampling_date`,
```

Is this expected behaviour?

**Comment by georgesittas** [comment]
Hey 👋

> Is this expected behaviour?

Yep, this is expected. Did you encounter any issues?

**Comment by hustic** [comment]
My initial intent was to use the fact that `SAFE_CAST` returns `NULL`, to try different `DATE FORMAT`s for all possible cases (and have `NULL` for the invalid ones). This is not possible as `PARSE_DATE` does not return `NULL` when it fails but raises an error.

Since this is expected, I'll use a Python Macro instead. 

Thanks for the quick response! ^^

**Comment by georgesittas** [comment]
Ah, I just saw that this is a `SAFE_CAST` and not a regular one. It actually does look like a bug, since the semantics are not preserved. I'll look into fixing this in SQLGlot, thanks!

**Comment by georgesittas** [comment]
@hustic fixed this upstream. Planning to do a patch release for sqlglot so the fix should be available soon.
