### ISSUE TITLE
Built in Audits using python

### ISSUE THREAD

**Issue by wleescor** [TobikoData/sqlmesh#2885]
Hi

I'm trying to use the `@model` decorator and python model to define a not_null audit, but can't find any documentation as to the correct syntax.
I am putting this into the `@model` decorator, with the argument for audits
`audits=['not_null'] `
gives Error: Macro variable 'columns' is undefined.
`audits=['not_null(columns:=(lastname))'] `
gives Error: Unknown audit 'not_null(columns:=(lastname))' 

The workaround is to create this sql script in the audits folder, and specifying audits ='nonnulls' but I'm assuming there should be a more concise way within the `@model` decorator without creating a user defined audit for built in non-null
```
AUDIT (
  name nonnulls,
);

SELECT *
FROM @this_model
WHERE
  LastName is null
```

Thanks

**Comment by georgesittas** [comment]
Hey, thanks for the report. It looks like this is indeed missing from the docs, we'll make sure to include it. In the meantime, take a look at https://github.com/TobikoData/sqlmesh/blob/main/examples/sushi/models/items.py#L63-L67.
