### ISSUE TITLE
Heap corruption during sqlmesh run

### ISSUE THREAD

**Issue by MikeWallis42** [TobikoData/sqlmesh#2932]
I've had this issue a few times now (although not consistently) and I'm not sure how I might go about debugging it further.
This time it happened during the tidy up process (janitor?) of `sqlmesh run`.
When running the command again it went straight in to modelling data so I might assume that it was at the end of that process.

I'm not sure what you might need so I'm using SQLMesh version 0.112.0, state is held in duckdb, engine is Trino.

![Screenshot 2024-07-24 at 08 27 23](https://github.com/user-attachments/assets/03ce0ca9-1285-4e5d-b97b-58c48d0218a2)

If I find a way of re-producing it consistently or find anymore information I'll add it to this bug.

**Comment by MikeWallis42** [comment]
Looks like on my last run it was something to do with duckdb.

![Screenshot 2024-07-24 at 09 20 54](https://github.com/user-attachments/assets/8d0d0705-dc33-4029-93ed-d7800ead20a2)

Below from the problem report, looks like duckdb resolved to version 1.0.0 in my poetry virtual environment.
I can appreciate this isn't an issue for SQLMesh specifically, however, I currently can't pinpoint an issue on the duckdb project that this might relate to however.

Thread 18 Crashed:
0   libsystem_kernel.dylib        	    0x7ff809c8214a __pthread_kill + 10
1   libsystem_pthread.dylib       	    0x7ff809cbaebd pthread_kill + 262
2   libsystem_c.dylib             	    0x7ff809be0a79 abort + 126
3   libsystem_malloc.dylib        	    0x7ff809ae53a9 malloc_vreport + 857
4   libsystem_malloc.dylib        	    0x7ff809b08c5b malloc_zone_error + 183
5   libsystem_malloc.dylib        	    0x7ff809afa389 nanov2_guard_corruption_detected + 34
6   libsystem_malloc.dylib        	    0x7ff809af9692 nanov2_allocate_outlined + 385
7   libsystem_malloc.dylib        	    0x7ff809ad83c7 nanov2_malloc + 537
8   libc++abi.dylib               	    0x7ff809c7534a operator new(unsigned long) + 26
9   duckdb.cpython-311-darwin.so  	       0x119bb4ae1 duckdb::TemplatedUniqueIf<duckdb::PhysicalTableScan, true>::templated_unique_single_t duckdb::make_uniq<duckdb::PhysicalTableScan, duckdb::vector<duckdb::LogicalType, true>&, duckdb::TableFunction&, duckdb::unique_ptr<duckdb::FunctionData, std::__1::default_delete<duckdb::FunctionData>, true>, duckdb::vector<duckdb::LogicalType, true>&, duckdb::vector<unsigned long long, true>&, duckdb::vector<unsigned long long, true>&, duckdb::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, true>&, duckdb::unique_ptr<duckdb::TableFilterSet, std::__1::default_delete<duckdb::TableFilterSet>, true>, unsigned long long&, duckdb::ExtraOperatorInfo&>(duckdb::vector<duckdb::LogicalType, true>&, duckdb::TableFunction&, duckdb::unique_ptr<duckdb::FunctionData, std::__1::default_delete<duckdb::FunctionData>, true>&&, duckdb::vector<duckdb::LogicalType, true>&, duckdb::vector<unsigned long long, true>&, duckdb::vector<unsigned long long, true>&, duckdb::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, true>&, duckdb::unique_ptr<duckdb::TableFilterSet, std::__1::default_delete<duckdb::TableFilterSet>, true>&&, unsigned long long&, duckdb::ExtraOperatorInfo&) + 577
10  duckdb.cpython-311-darwin.so  	       0x119bb357b duckdb::PhysicalPlanGenerator::CreatePlan(duckdb::LogicalGet&) + 571
11  duckdb.cpython-311-darwin.so  	       0x1198bce66 duckdb::PhysicalPlanGenerator::CreatePlan(duckdb::LogicalOperator&) + 854
12  duckdb.cpython-311-darwin.so  	       0x119bb71af duckdb::PhysicalPlanGenerator::CreatePlan(duckdb::LogicalProjection&) + 63
13  duckdb.cpython-311-darwin.so  	       0x1198bce9e duckdb::PhysicalPlanGenerator::CreatePlan(duckdb::LogicalOperator&) + 910
14  duckdb.cpython-311-darwin.so  	       0x1198bca3b duckdb::PhysicalPlanGenerator::CreatePlan(duckdb::unique_ptr<duckdb::LogicalOperator, std::__1::default_delete<duckdb::LogicalOperator>, true>) + 379
15  duckdb.cpython-311-darwin.so  	       0x119f6786c duckdb::ClientContext::CreatePreparedStatementInternal(duckdb::ClientContextLock&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, duckdb::unique_ptr<duckdb::SQLStatement, std::__1::default_delete<duckdb::SQLStatement>, true>, duckdb::optional_ptr<std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, duckdb::Value, duckdb::CaseInsensitiveStringHashFunction, duckdb::CaseInsensitiveStringEquality, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, duckdb::Value>>>>) + 1532
16  duckdb.cpython-311-darwin.so  	       0x119f6851e duckdb::ClientContext::CreatePreparedStatement(duckdb::ClientContextLock&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, duckdb::unique_ptr<duckdb::SQLStatement, std::__1::default_delete<duckdb::SQLStatement>, true>, duckdb::optional_ptr<std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, duckdb::Value, duckdb::CaseInsensitiveStringHashFunction, duckdb::CaseInsensitiveStringEquality, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, duckdb::Value>>>>, duckdb::PreparedStatementMode) + 414
17  duckdb.cpython-311-darwin.so  	       0x119fd707d std::__1::__function::__func<duckdb::ClientContext::PrepareInternal(duckdb::ClientContextLock&, duckdb::unique_ptr<duckdb::SQLStatement, std::__1::default_delete<duckdb::SQLStatement>, true>)::$_1, std::__1::allocator<duckdb::ClientContext::PrepareInternal(duckdb::ClientContextLock&, duckdb::unique_ptr<duckdb::SQLStatement, std::__1::default_delete<duckdb::SQLStatement>, true>)::$_1>, void ()>::operator()() + 61
18  duckdb.cpython-311-darwin.so  	       0x119f6a866 duckdb::ClientContext::RunFunctionInTransactionInternal(duckdb::ClientContextLock&, std::__1::function<void ()> const&, bool) + 118
19  duckdb.cpython-311-darwin.so  	       0x119f6b18a duckdb::ClientContext::PrepareInternal(duckdb::ClientContextLock&, duckdb::unique_ptr<duckdb::SQLStatement, std::__1::default_delete<duckdb::SQLStatement>, true>) + 346
20  duckdb.cpython-311-darwin.so  	       0x119f6b71f duckdb::ClientContext::Prepare(duckdb::unique_ptr<duckdb::SQLStatement, std::__1::default_delete<duckdb::SQLStatement>, true>) + 159
21  duckdb.cpython-311-darwin.so  	       0x119f78e76 duckdb::Connection::Prepare(duckdb::unique_ptr<duckdb::SQLStatement, std::__1::default_delete<duckdb::SQLStatement>, true>) + 54
22  duckdb.cpython-311-darwin.so  	       0x11a41dbcd duckdb::DuckDBPyConnection::ExecuteInternal(duckdb::vector<duckdb::unique_ptr<duckdb::SQLStatement, std::__1::default_delete<duckdb::SQLStatement>, true>, true>, pybind11::object, bool) + 541
23  duckdb.cpython-311-darwin.so  	       0x11a41cf1a duckdb::DuckDBPyConnection::Execute(pybind11::object const&, pybind11::object, bool) + 106
24  duckdb.cpython-311-darwin.so  	       0x11a437ec9 duckdb::shared_ptr<duckdb::DuckDBPyConnection, true> pybind11::detail::argument_loader<duckdb::DuckDBPyConnection*, pybind11::object const&, pybind11::object, bool>::call_impl<duckdb::shared_ptr<duckdb::DuckDBPyConnection, true>, pybind11::cpp_function::cpp_function<duckdb::shared_ptr<duckdb::DuckDBPyConnection, true>, duckdb::DuckDBPyConnection, pybind11::object const&, pybind11::object, bool, pybind11::name, pybind11::is_method, pybind11::sibling, char [86], pybind11::arg, pybind11::arg_v, pybind11::arg_v>(duckdb::shared_ptr<duckdb::DuckDBPyConnection, true> (duckdb::DuckDBPyConnection::*)(pybind11::object const&, pybind11::object, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&, char const (&) [86], pybind11::arg const&, pybind11::arg_v const&, pybind11::arg_v const&)::'lambda'(duckdb::DuckDBPyConnection*, pybind11::object const&, pybind11::object, bool)&, 0ul, 1ul, 2ul, 3ul, pybind11::detail::void_type>(duckdb::DuckDBPyConnection&&, pybind11::detail::index_sequence<0ul, 1ul, 2ul, 3ul>, pybind11::detail::void_type&&) && + 89
25  duckdb.cpython-311-darwin.so  	       0x11a437b84 void pybind11::cpp_function::initialize<pybind11::cpp_function::cpp_function<duckdb::shared_ptr<duckdb::DuckDBPyConnection, true>, duckdb::DuckDBPyConnection, pybind11::object const&, pybind11::object, bool, pybind11::name, pybind11::is_method, pybind11::sibling, char [86], pybind11::arg, pybind11::arg_v, pybind11::arg_v>(duckdb::shared_ptr<duckdb::DuckDBPyConnection, true> (duckdb::DuckDBPyConnection::*)(pybind11::object const&, pybind11::object, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&, char const (&) [86], pybind11::arg const&, pybind11::arg_v const&, pybind11::arg_v const&)::'lambda'(duckdb::DuckDBPyConnection*, pybind11::object const&, pybind11::object, bool), duckdb::shared_ptr<duckdb::DuckDBPyConnection, true>, duckdb::DuckDBPyConnection*, pybind11::object const&, pybind11::object, bool, pybind11::name, pybind11::is_method, pybind11::sibling, char [86], pybind11::arg, pybind11::arg_v, pybind11::arg_v>(duckdb::shared_ptr<duckdb::DuckDBPyConnection, true>&&, duckdb::DuckDBPyConnection (*)(pybind11::object const&, pybind11::object, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&, char const (&) [86], pybind11::arg const&, pybind11::arg_v const&, pybind11::arg_v const&)::'lambda'(pybind11::detail::function_call&)::operator()(pybind11::detail::function_call&) const + 116
26  duckdb.cpython-311-darwin.so  	       0x11a437b04 void pybind11::cpp_function::initialize<pybind11::cpp_function::cpp_function<duckdb::shared_ptr<duckdb::DuckDBPyConnection, true>, duckdb::DuckDBPyConnection, pybind11::object const&, pybind11::object, bool, pybind11::name, pybind11::is_method, pybind11::sibling, char [86], pybind11::arg, pybind11::arg_v, pybind11::arg_v>(duckdb::shared_ptr<duckdb::DuckDBPyConnection, true> (duckdb::DuckDBPyConnection::*)(pybind11::object const&, pybind11::object, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&, char const (&) [86], pybind11::arg const&, pybind11::arg_v const&, pybind11::arg_v const&)::'lambda'(duckdb::DuckDBPyConnection*, pybind11::object const&, pybind11::object, bool), duckdb::shared_ptr<duckdb::DuckDBPyConnection, true>, duckdb::DuckDBPyConnection*, pybind11::object const&, pybind11::object, bool, pybind11::name, pybind11::is_method, pybind11::sibling, char [86], pybind11::arg, pybind11::arg_v, pybind11::arg_v>(duckdb::shared_ptr<duckdb::DuckDBPyConnection, true>&&, duckdb::DuckDBPyConnection (*)(pybind11::object const&, pybind11::object, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&, char const (&) [86], pybind11::arg const&, pybind11::arg_v const&, pybind11::arg_v const&)::'lambda'(pybind11::detail::function_call&)::__invoke(pybind11::detail::function_call&) + 20
27  duckdb.cpython-311-darwin.so  	       0x11a3a9681 pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 4881
28  Python                        	       0x10ab957e3 cfunction_call + 53
29  Python                        	       0x10ab4f4e1 _PyObject_MakeTpCall + 273
30  Python                        	       0x10ab52c00 method_vectorcall + 570
31  Python                        	       0x10ac2b170 _PyEval_EvalFrameDefault + 54857
32  Python                        	       0x10ac2d930 _PyEval_Vector + 92
33  Python                        	       0x10ab52a8f method_vectorcall + 201
34  Python                        	       0x10ac2b170 _PyEval_EvalFrameDefault + 54857
35  Python                        	       0x10ac2d930 _PyEval_Vector + 92
36  Python                        	       0x10ab52a8f method_vectorcall + 201
37  Python                        	       0x10ac2b170 _PyEval_EvalFrameDefault + 54857
38  Python                        	       0x10ac2d930 _PyEval_Vector + 92
39  Python                        	       0x10ab52a8f method_vectorcall + 201
40  Python                        	       0x10ac2b170 _PyEval_EvalFrameDefault + 54857
41  Python                        	       0x10ac2d930 _PyEval_Vector + 92
42  Python                        	       0x10ac2b170 _PyEval_EvalFrameDefault + 54857
43  Python                        	       0x10ac2d930 _PyEval_Vector + 92
44  Python                        	       0x10ab52b70 method_vectorcall + 426
45  Python                        	       0x10ace1a8d thread_run + 163
46  Python                        	       0x10ac857a2 pythread_wrapper + 36
47  libsystem_pthread.dylib       	    0x7ff809cbb18b _pthread_start + 99
48  libsystem_pthread.dylib       	    0x7ff809cb6ae3 thread_start + 15

Thread 18 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000006  rcx: 0x0000700006d9aa08  rdx: 0x0000000000000000
  rdi: 0x0000000000002e07  rsi: 0x0000000000000006  rbp: 0x0000700006d9aa30  rsp: 0x0000700006d9aa08
   r8: 0x000000000000002e   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000246
  r12: 0x0000000000002e07  r13: 0x0000000000000043  r14: 0x0000700006d9d000  r15: 0x0000000000000016
  rip: 0x00007ff809c8214a  rfl: 0x0000000000000246  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x02000148 
Trap Number:     133

**Comment by tobymao** [comment]
This looks like a duckdb issue. I'd suggest making an issue with them. I'd suggest either using [Cloud](https://tobikodata.com/product.html) or Postgres if a DuckDB version change doesn't fix the issue.

**Comment by MikeWallis42** [comment]
Thank you for confirming
