### ISSUE TITLE
Should python macro functions work in audits?

### ISSUE THREAD

**Issue by patricksurry** [TobikoData/sqlmesh#2948]
In the example project, I added macros/constants.py containing 
```python
from sqlmesh import macro
from sqlmesh.core.macros import MacroEvaluator

@macro()
def min_item(
    evaluator: MacroEvaluator
) -> int:
    return 0
```

I modified models/incremental_model.sql to reference it like this:
```sql
...
WHERE
  event_date BETWEEN @start_date AND @end_date
  and item_id > @min_item()
``` 

which works just fine.  But if I also modify audits/assert_positive_order_ids.sql to reference it:
```sql
...
SELECT
  *
FROM @this_model
WHERE
  item_id < @min_item()
```

then it fails to find the macro:
```sh
sqlmesh-example % sqlmesh audit                                   
Error: Macro 'min_item' does not exist.

sqlmesh-example % sqlmesh --version
0.113.0
```

**Comment by izeigerman** [comment]
I believe we don't scan audits for macro references when constructing the model's python environment. This is why the macro can't be found.

@georgesittas , @Themiscodes can either of you please have a look when you get a chance.

**Comment by Themiscodes** [comment]
Sure, I will look into it
