### ISSUE TITLE
[Q] In multi repo example how to create an external model in one repo that references the local db of other repo?

### ISSUE THREAD

**Issue by fredguth** [TobikoData/sqlmesh#2976]
Imagine a scenario where the warehouse is simply a duckdb file, maintained in a root repo and different subteams have their own schema in the warehouse and repo on github which are sub modules of the root repo (it would be easier to have it all in one repo but different teams need to interact with different external devs and we would like to prevent giving access to the main repo.)

What is the best practice for a subteam reference other teams schemas?

**Comment by eakmanrq** [comment]
Context: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1722630215473949
