### ISSUE TITLE
Invalid model error does not tell you which and how many files are affected

### ISSUE THREAD

**Issue by quassy** [TobikoData/sqlmesh#3040]
If you get an error for an invalid model, the error message is missing any information on which SQL file is invalid:

> Error: The model definition must either have a SELECT query, a JINJA_QUERY block, or a valid Seed kind. 1 validation error for SeedKind
> path
>   Field required [type=missing, input_value={}, input_type=dict]
>     For further information visit https://errors.pydantic.dev/2.7/v/missing.

For example for any model without SELECT / only with DML, you'll obviously get an error once you run `sqlmesh plan` (`--verbose` does not actually include any more information) or check via `sqlmesh ui`. While this is expected, it would be very helpful to get information which model file is the cause.

Additionally, even if you have multiple invalid model files, there is only one error message.

Example of invalid model file to reproduce the issue:

```sql
-- api/users.sql
MODEL (
    kind FULL,
    name users
);

INSERT INTO api.users (id, name)  -- this line causes the error
SELECT 1, 'Peter';
```

**Comment by akv-akv** [comment]
Added fix: #3045
