### ISSUE TITLE
Add option to store audit failures in database

### ISSUE THREAD

**Issue by fredguth** [TobikoData/sqlmesh#3064]
# Store SQLMesh Audit Failures for Later Consumption

## Summary
Add an option to `sqlmesh audit` to store failed audit results in a table for later analysis and reporting.

## Background
Similar features exist in other data tools:
- dbt: [store_failures](https://docs.getdbt.com/reference/resource-configs/store_failures)
- Dataform: [Assertions](https://cloud.google.com/dataform/docs/assertions#about_assertions)

## Use Case
Storing failed audit results enables:
- Historical tracking of audit performance
- Integration with data catalogs and quality dashboards
- Detailed analysis of failure patterns

Example: Generating a data catalog with a "Quality" tab showing all audits and their results, similar to Great Expectations Cloud.

### 1. Create a new table for failed audits

```sql
SELECT * FROM audits.failed
```

Example output:

| project   | model   | audit_id | audit_description | query                 | failed | audited_at                 |
|-----------|---------|----------|-------------------|----------------------|--------|----------------------------|
| Project A | Model X | audit_1  | Initial audit     | SELECT * ...         | true   | 2024-08-28 07:56:36.366-03 |
| Project B | Model Y | audit_2  | ...               | ...                  | false  | 2024-08-28 07:56:36.366-03 |
| Project C | Model Y | audit_3  | ...               | ...                  | false  | 2024-08-28 07:56:36.366-03 |

### 2. Store detailed failure information

For each failed audit, create a separate table with failure details:

```sql
SELECT * FROM audits.audit_1
```

### Alternative: JSON Export
Consider exporting failed values as a JSON object for flexibility.

## Implementation Details
- [ ] Add a new command-line option to `sqlmesh audit` (e.g., `--store-failures`)
- [ ] Implement logic to create and populate the `audits.failed` table
- [ ] Create individual tables for each failed audit 
- [ ] (Optional) Implement JSON export functionality

## Questions
- How long should failed audit data be retained?
- Is there a way to store any kind of audit failure in the same `assertion_table` independent of the model and the audit query?

**Comment by fredguth** [comment]
Is there any plan on building this feature?  Is there a suggested temporary solution?

**Comment by tobymao** [comment]
no there are no plans for this since this is already in in tobiko cloud

**Comment by Harmuth94** [comment]
> Are there any plans to implement this feature? In the meantime, is there a recommended temporary solution?

Going by the implementation of the audit command, it calls the [`audit` function in `context.py`](https://github.com/TobikoData/sqlmesh/blob/2cf49be01d0f809b3da17c029fe668e6a073e043/sqlmesh/core/context.py)

What you basically want is to use the `python` interface to SQLMesh and manually run the audits as defined in the `context.audit()` function. 

```python
from sqlmesh.core.context import Context
context = Context(paths="example")
start, end = "yesterday", "now"

snapshots = context.snapshots.values()

for snapshot in snapshots:
    for audit_result in context.snapshot_evaluator.audit(
        snapshot=snapshot,
        start=start,
        end=end,
        snapshots=context.snapshots,
        raise_exception=False,
    ):
        if audit_result.count:
            if audit_result.query:
                query_with_failed_results = audit_result.query
                # use the query to save to table, insert, etc.
```

**Comment by fredguth** [comment]
> Going by the implementation of the audit command, it calls the [`audit` function in `context.py`](https://github.com/TobikoData/sqlmesh/blob/2cf49be01d0f809b3da17c029fe668e6a073e043/sqlmesh/core/context.py)
> 
> What you basically want is to use the `python` interface to SQLMesh and manually run the audits as defined in the `context.audit()` function.
> 
@Harmuth94 Did you have the same problem?  I understood you took the approach you laid down and created your own audit command, right?

**Comment by Harmuth94** [comment]
Well actually we changed the audits to models with a `validated` column (to persist) and then a simple audit on top to `select id from table where not validated`
