### ISSUE TITLE
postgres requires airflow?

### ISSUE THREAD

**Issue by vacquah** [TobikoData/sqlmesh#3065]
Doing a `pip install "sqlmesh[postgres]"` also requires an airflow cluster?  The documentation also says. "The operator requires an [Airflow connection](https://airflow.apache.org/docs/apache-airflow/stable/howto/connection.html) to determine the target Postgres account." - What if I am not using airlfow at all?

**Comment by tobymao** [comment]
sqlmesh postgres does not require airflow an airflow connection. the documentation that you linked is in airflow and not postgres. 

when you run pip install sqlmesh[postgres], it does not install airflow

**Comment by vacquah** [comment]
I am having issues running `pip install sqlmesh[postgres]` on an ubunut 22.04 machine.  The errors are related to the install on psycopg. I installed `psycopg2-binary `manually and tried again. Got the error below:

```
      In file included from psycopg/adapter_asis.c:28:
      ./psycopg/psycopg.h:35:10: fatal error: Python.h: No such file or directory
         35 | #include <Python.h>
            |          ^~~~~~~~~~
      compilation terminated.
      
      It appears you are missing some prerequisite to build the package from source.
      
      You may install a binary package by installing 'psycopg2-binary' from PyPI.
      If you want to install psycopg2 from source, please install the packages
      required for the build and try again.
      
      For further information please check the 'doc/src/install.rst' file (also at
      <https://www.psycopg.org/docs/install.html>).
      
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> psycopg2

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```
