### ISSUE TITLE
Using `/deploy` while a `restate-model` plan is running causes the `/deploy` plan to compute intervals of the `restate-model` plan

### ISSUE THREAD

**Issue by plaflamme** [TobikoData/sqlmesh#3066]
Assume that an expensive `restate-model` plan is running and computing batches of intervals for model `restated_model`. Using `/deploy` on an open PR (which does not modify or depend on `restated_model`) will start backfilling that PR's model(s), but it will **also** compute intervals for `restated_model`. This causes the `restate-model` plan and the `/deploy` plan to compute the same intervals, potentially concurrently. Normally, the `/deploy` plan should only consider the models that it is affecting.

The bot's configuration is as follows:

```
GithubCICDBotConfig(
  merge_method="squash",
  enable_deploy_command=True,
  auto_categorize_changes=CategorizerConfig.all_full(),
  default_pr_start="1 day ago",
  skip_pr_backfill=True,
  run_on_deploy_to_prod=False,
),
```

**Comment by tobymao** [comment]
I think this is something we plan to tackle with our enterprise bot, scheduler, and plan service, so closing this for now.
