### ISSUE TITLE
Snowflake Secure View Support

### ISSUE THREAD

**Issue by isaiahgm** [TobikoData/sqlmesh#3070]
[Secure views](https://docs.snowflake.com/en/user-guide/views-secure#overview-of-secure-views) are feature in Snowflake that allows engineers to obfuscate the view query code and must be used when sharing views across Snowflake Account using [Snowflake Data Sharing](https://docs.snowflake.com/en/user-guide/data-sharing-provider#general-data-sharing-considerations-and-usage).

Because SQL Mesh only surfaces data for end users as views, we are unable to share data created by SQL Mesh with other Snowflake Accounts, which limits SQL Mesh's potential use cases.

I propose adding this functionality either as another option in the model configuration or as a key pair in the virtual properties config option.

**Comment by BenKentzer** [comment]
Hello!
+1 for this feature, but there is a slightly messy work around...
https://docs.snowflake.com/en/user-guide/data-sharing-views

Secure views as an option will e gratefully received here too!

**Comment by benfdking** [comment]
This was released in the latest version and is documented below. 

https://sqlmesh.readthedocs.io/en/stable/integrations/engines/snowflake/#secure-views
