### ISSUE TITLE
Sqlmesh UI on constant refresh

### ISSUE THREAD

**Issue by RN-nguyen** [TobikoData/sqlmesh#3109]
Loaded up wursthall and sushi_dbt in sqlmesh ui and getting a refresh no matter what page I am on. 

Here is a video showing what's happening on my end. I am not doing anything when the page is refreshing here:

https://github.com/user-attachments/assets/4dae62d3-9b49-41fe-b00c-1fedcd1ee642

**Comment by tobymao** [comment]
@mykalmax can you take a look?

**Comment by RN-nguyen** [comment]
Verified branch addresses refreshing issue related to file watcher.
Also able to create, update, delete new files and folders.
