### ISSUE TITLE
Airfloe: daemonic processes are not allowed to have children

### ISSUE THREAD

**Issue by sammywachtel** [TobikoData/sqlmesh#3121]
Version: v0.121.1

Upgraded from v0.118.0 and found Airflow to be unable to import the sqlmesh_integration.py DAG with the error: `AssertionError: daemonic processes are not allowed to have children`

I believe the issue to be tied to the 9/5/24 change here: https://github.com/TobikoData/sqlmesh/pull/3097/files#diff-aee9f4740fd05cff585a985f6a133a3e12c43a9853882262aef664427e3f9201R39

It seems that when running airflow in a local docker container `mp.current_process().daemon` returns False instead. I wonder if Airflow uses system-level processes or workers that don't follow the multiprocessing daemon model.

Setting `MAX_FORK_WORKERS=1` env variable gets around the issue.

**Comment by tobymao** [comment]
i think the solution for now is to just set max_fork_workers=1
