### ISSUE TITLE
Top level notification_targets don't seem to respect notify_on

### ISSUE THREAD

**Issue by patricksurry** [TobikoData/sqlmesh#3145]
We removed `audit_failure` from our top level `config::notification_targets.notify_on` list, because audit failures seem to have become noisier recently (they include the audit SQL).   But this doesn't seem to stop the notifications.  

I don't pretend to understand all the code but it seems like perhaps [this check](https://github.com/TobikoData/sqlmesh/blob/f7e4c477507b3862e2ee355461338a88b93a3e14/sqlmesh/core/notification_target.py#L471) should also appear around [here](https://github.com/TobikoData/sqlmesh/blob/f7e4c477507b3862e2ee355461338a88b93a3e14/sqlmesh/core/notification_target.py#L461) ?

**Comment by izeigerman** [comment]
@patricksurry this is a great catch, thank you! @vchan can you please confirm that this is the root cause

**Comment by vchan** [comment]
Yes, I'll take a look.

**Comment by vchan** [comment]
@patricksurry Thanks for reporting your issue. I am unable to reproduce it though. Are you able to provide more information on when you're encountering the notification? Is it during a run?

**Comment by patricksurry** [comment]
We updated our `config.py` to look like below, but still getting audit failure notifications in channel xxx.   I'll explore some more and see if there's some issue on our side.

```
USERS = [ ... ]

notification_targets = []
if "SLACK_API_TOKEN" in os.environ:
    notification_targets.append(
        SlackApiNotificationTarget(
            notify_on=[
                "apply_start",
                "apply_failure",
                "apply_end",
                "run_start",
                "run_end",
                "run_failure",
                # ===>   removed "audit_failure" here  <===
            ],
            token=os.getenv("SLACK_API_TOKEN"),
            channel="xxx",  
        )
    )

    for user in USERS:
        user.notification_targets.append(
            SlackApiNotificationTarget(
                notify_on=["audit_failure"],
                token=os.getenv("SLACK_API_TOKEN"),
                channel="yyy", 
            )
        )

config = Config(
    users=USERS,
    notification_targets=notification_targets,
    ...
)
```

**Comment by vchan** [comment]
Your config looks fine to me. I'll keep investigating on my end as well. Are you seeing the unwanted notifications when running plan locally?

We build a mapping of events to notification targets [here](https://github.com/TobikoData/sqlmesh/blob/c742bcb5978c1bc10a70a0ecda4bd0530c283c99/sqlmesh/core/context.py#L2049). That is why the check is not needed in the notify function you linked.

**Comment by patricksurry** [comment]
hmm, i wonder if we are triggering them thru user notifications to a shared channel.

**Comment by patricksurry** [comment]
yes, my bad - you can close this as mistaken.  it seems like we were routing user notifications to the shared channel which explains why the configuration change had no apparent effect
