### ISSUE TITLE
[web] feature request / pull request: sqlglot / pyodide offline support

### ISSUE THREAD

**Issue by barakplasma** [TobikoData/sqlmesh#3148]
### Discussed in https://github.com/TobikoData/sqlmesh/discussions/3142

<div type='discussions-op-text'>

<sup>Originally posted by **barakplasma** September 17, 2024</sup>
can we inline pyodide / sqlglot into the web/client/src/assets folder for offline support? For environments with a firewall for example? Feels weird to make requests to jsdelivr.net every time I want to format some sql </div>

Toby said sure.

Design: use https://github.com/pyodide/pyodide-pack to make a bundle of all the pip libraries etc
See also https://pyodide-pack.pyodide.org/en/latest/module-elimination-at-runtime.html

I'll attempt to implement it and make a PR, but feel free to do it yourselves as well

**Comment by tobymao** [comment]
we don’t have plans to implement this, but will accept a pr, i’m going to close this issue, but we’ll work with you on the pr
