### ISSUE TITLE
Kind = INCREMENTAL_BY_TIME_RANGE, time_column is not part of the Model 

### ISSUE THREAD

**Issue by wahmedswl** [TobikoData/sqlmesh#3180]
Hi!

```
MODEL (
  name medallion.gl_providers_practice,
  kind INCREMENTAL_BY_TIME_RANGE (
    time_column created_at
  ),
  start '2020-01-01',
  cron '@daily',
  grain (full_name)
);

SELECT
  practice_name,
  active,
  count(full_name) total_providers
FROM
  medallion.sl_providers
WHERE
  created_at BETWEEN @start_date AND @end_date
GROUP BY community_name, active

```

I am getting ```Error: partitioned_by keys ['created_at'] are missing in the model definition at '/home/wahmed/medallion-sqlmesh/models/gold/providers_by_practice.sql'```. Referenced model has field ```created_at``` and defined like 

```
MODEL (
  name medallion.sl_providers,
  kind FULL,
  cron '@daily',
  grain full_name,
);

SELECT
  'N/A' as community_name,
  'N/A' as practice_name,
  'N/A' as location_name,
  FullName AS full_name,
  Active AS active,
  CreatedAt as created_at
FROM
  medallion.bl_providers
```

This is KPI table and it will contain incremental data rather than building full table. So, am I doing something wrong?

Thanks

**Comment by tobymao** [comment]
You need to have created_at as a column/projection in your incremental model.

your SELECT statement for gl_providers_practice is missing the created_at field.

**Comment by wahmedswl** [comment]
@tobymao but why? as data is pulled from sl_providers and it already have created_at field. This is KPI and computed via the sl_providers data, we just want it to be incremental.

**Comment by tobymao** [comment]
SQLMesh requires incremental models to have a time column, that way you know what time range a particular row is associated with.

**Comment by wahmedswl** [comment]
But this model doesn't require one. Is this time_column used in the current model as well? I have defined this model like this right now

```
MODEL (
  name medallion.gl_providers_practice,
  kind INCREMENTAL_BY_TIME_RANGE (
    time_column created_at
  ),
  start '2020-01-01',
  cron '@daily',
  grain (full_name)
);

SELECT
  practice_name,
  active,
  NULL AS created_at,
  count(full_name) total_providers
FROM
  medallion.sl_providers
WHERE
  created_at BETWEEN @start_date AND @end_date
GROUP BY practice_name, active
```

**Comment by tobymao** [comment]
It is a requirement in SQLMesh for incremental_by_time_range models to have a time column. Otherwise we won't be able to delete + insert segments of data.

**Comment by z3z1ma** [comment]
This seems like a case of an XY problem. Why don't you share _exactly_ what you want/expect the output table to look like across multiple runs?

If your goal is that the output table is a mutable roll up of the underlying data, then incremental by time range is the wrong model. You probably want incremental by unique key. And you can use a custom when matched to sum the provider count. In this way, you can still read the upstream table in increments. 

Incremental by time range is used to construct a table with an output partition for every interval unit.

**Comment by wahmedswl** [comment]
@tobymao and @z3z1ma I understand now, i used the wrong abstraction and data model also seems to be wrong. I wanted to have the KPI table have incremental data but with aggregate will not work like this. @z3z1ma incremental by unique key will not also work because frankly it cannot be built incrementally. 

Thanks for your help, really appreciate that.
