### ISSUE TITLE
Converting an `INCREMENTAL_BY_TIME` model to a `VIEW` model as a forward-only plan fails in BigQuery

### ISSUE THREAD

**Issue by plaflamme** [TobikoData/sqlmesh#3196]
The generated query from sqlmesh is something like

```
CREATE OR REPLACE VIEW ...
```

But BigQuery fails with the following error:

```
<table_snapshot_id> is not allowed for this operation because it is currently a TABLE.
```

So because the physical table is a `TABLE` (not a view), you cannot use `CREATE OR REPLACE VIEW` (you could only use `CREATE OR REPLACE TABLE`).

**Comment by izeigerman** [comment]
Model kind changes should be categorized as `BREAKING` even if it's a forward-only plan.
