### ISSUE TITLE
[feature] Incremental + view model for streamed raw data

### ISSUE THREAD

**Issue by jonathan-ostrander** [TobikoData/sqlmesh#3198]
## Context

Most of the data warehouse engines support streaming data ingestion. Querying real-time data is useful in specific cases like validation and debugging, but in most cases this data is raw and not useful to query as-is. It may also be expensive to query if the raw data is in an unstructured format e.g. 1 column with a JSON blob.

Materialized views are useful for helping with this problem but they tend to be very rigid and inefficient to manage. For example, updating the schema of a materialized view in BigQuery requires recreating the materialization which can be very expensive for large tables. `INCREMENTAL_BY_TIME_RANGE` models help with efficiently structuring the data into a materialized table but the data is no longe real-time. As a compromise between these options, a view for the "real-time" data could be created to supplement the `INCREMENTAL_BY_TIME_RANGE` table but implementing this with SQLMesh as-is is tedious.

## Example

Let's say we have a large table called `foo_unstructured` with 2 columns, `ts TIMESTAMP` and `value JSON`, which is partitioned on `DATE(ts)`. On top of this we want to have a view called `foo_structured` which is the following transformation:

```sql
SELECT
  JSON_VALUE(value, "$.id") AS id,
  ts,
  JSON_VALUE(value, "$.bar") AS bar,
  CAST(JSON_VALUE(value, "$.baz") AS NUMERIC) AS baz
FROM foo_unstructured
```

If we implemented this as a materialized view, then adding a column like `JSON_VALUE(value, "$.qux") AS qux` would require rematerializing the whole table even if `qux` was only added recently. If we implemented this as an `INCREMENTAL_BY_TIME_RANGE` model then adding the column can be efficient because we can specify that the change is forward only or invalidating specific intervals that include the new column, but the model will not be real-time.

## Workaround

Currently with SQLMesh we can work around the issue with `INCREMENTAL_BY_TIME_RANGE` by doing the following:

* Keep the `INCREMENTAL_BY_TIME_RANGE` model but call it something like `foo_structured_materialized`
* Create a `VIEW` model called something like `foo_structured_intermediate_view` with the same exact query as `foo_structured_materialized` except change the partition filter to `ts > @end_ts` where `@end_ts` is the end of the last interval that was ran for `foo_structured_materialized`
* Create a `VIEW` model called `foo_structured` that is
```sql
SELECT * FROM foo_structured_materialized
UNION ALL
SELECT * FROM foo_structured_intermediate_view
```

This is essentially recreating the logic for materialized views with added flexibility for handling schema updates.

## Proposal

While the above workaround should be possible with SQLMesh as-is (I'm not entirely sure about how to implement the `ts > @end_ts` filter for `foo_structured_intermediate_view` but I think it should be possible with a Python SQL model), it would be cumbersome/hacky to implement. I propose that a new model kind (e.g. `INCREMENTAL_BY_TIME_RANGE_WITH_REAL_TIME_VIEW` but I'm open to suggestions...) or property (`with_real_time_view: boolean`) be added to SQLMesh that would automatically handle the underlying materialization and intermediate view and only expose the real time view.

**Comment by tobymao** [comment]
I'm not sure this is necessary and I'm not too sold that we need this. 

A couple options. 

1. You can change the cron of foo_structured_materialized to be 5 minute cron.
2. You can run it with allow_partials to materialize sooner than that.
3. Do embedded -> materialized -> view where view does something like

SELECT *
FROM materialized
UNION ALL
SELECT * 
FROM embedded
WHERE (ts > (select max(ts) from materialized))

I'm going to close this for now, but happy to discuss more.
