### ISSUE TITLE
Add severity level for audits

### ISSUE THREAD

**Issue by patricksurry** [TobikoData/sqlmesh#3209]
Audits are very useful for monitoring data quality in sqlmesh.   However they currently feel a bit all-or-nothing making it difficult to cope with messy real-world data.   We currently need to have almost all audits set as 'non-blocking' since most surface at least a few known failures with our legacy data.    

It'd be really helpful to have a configurable severity level, along the lines of [sodaCL](https://docs.soda.io/soda-cl/optional-config.html#add-alert-configurations) pass/warn/fail model.    Alerts would still block if they fail, but not if they warned.  For example, a column should be unique, or non-null but allow 1% failure rate before failing the run.  This would allow tuning of e.g. slack alerts to reduce expected noise, analogous to python logging levels, and would let us manage down towards zero failures in a sensible way

If sqlmesh started storing audit results as per #3064, thresholds might even be relative to a previous result: fail if the percentage of null values increased from the previous value.   We normally care most when data quality is going backwards rather than perfect vs imperfect.

I understand if this issue is antithetical to the spirit of sqlmesh but would be very useful for us in practice...

**Comment by tobymao** [comment]
You can in your audit write logic that allows for 1% uniqueness. So i'm not exactly sure what pass / warn / fail would add. If you want your audit to be more forgiving, then you can write SQL to accomodate for that.

In terms of run over run changes and tracking numbers, this is available in our enterprise offering. 

https://sqlmesh.readthedocs.io/en/stable/guides/observer/?h=obs
