### ISSUE TITLE
Feature[Postgres]: allow for consistent snapshot to be used

### ISSUE THREAD

**Issue by judahrand** [TobikoData/sqlmesh#3237]
Postgres allows for exporting transaction snapshots to be reused between clients with [pg_export_snapshot](https://www.postgresql.org/docs/current/functions-admin.html#FUNCTIONS-SNAPSHOT-SYNCHRONIZATION). Sometimes, when replicating data it is important that this like foreign key relationships are maintained. It would be absolutely fantastic if for a given SQLMesh run a single Repeatable Read snapshot could be used. 

This would involve:

- Open one long lived transaction for the SQLMesh run and use `BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ; SELECT pg_export_snapshot();` to export a snapshot identifier.
- For any subsequent transaction which reads from the database run `BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ; SET TRANSACTION SNAPSHOT '00000003-0000001B-1';` where the snapshot identifier used is the one given by the long lived transaction.
- Make sure that the long lived transaction is closed when the SQLMesh run has either completed or failed.

**Comment by judahrand** [comment]
Thinking about this some more this might not be easy given that downstream models might want to query newer versions of upstream models. I suppose the consistent snapshot should really only be used for querying `source` tables.

**Comment by tobymao** [comment]
not sure how much appetite there is for this so closing for now
