### ISSUE TITLE
Comments are parsed for nodes while using DuckDB + Dbt +

### ISSUE THREAD

**Issue by cnstlungu** [TobikoData/sqlmesh#3241]
Hello! 

I'm using Duckdb + Duckdb in SQLMesh.

Looks like a reference inside a comment (which does not exist yet) triggers an error that it does not exist.

<img width="1144" alt="image" src="https://github.com/user-attachments/assets/15d5480b-95c6-40fd-8d05-2e515ced686f">

My environment:

agate==1.9.1
annotated-types==0.7.0
anyio==4.6.0
astor==0.8.1
asttokens==2.4.1
attrs==23.2.0
Babel==2.15.0
certifi==2024.7.4
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
comm==0.2.2
croniter==3.0.3
daff==1.3.46
dateparser==1.2.0
dbt-adapters==1.3.2
dbt-common==1.6.0
dbt-core==1.8.3
dbt-duckdb==1.8.1
dbt-extractor==0.5.1
dbt-semantic-interfaces==0.5.1
decorator==5.1.1
deepdiff==7.0.1
duckdb==1.0.0
exceptiongroup==1.2.2
executing==2.1.0
fastapi==0.110.2
freezegun==1.5.1
h11==0.14.0
httptools==0.6.1
hyperscript==0.2.0
idna==3.7
importlib-metadata==6.11.0
ipython==8.18.1
ipywidgets==8.1.5
isodate==0.6.1
jedi==0.19.1
Jinja2==3.1.4
jsonschema==4.23.0
jsonschema-specifications==2023.12.1
jupyterlab_widgets==3.0.13
leather==0.4.0
Logbook==1.5.3
markdown-it-py==3.0.0
MarkupSafe==2.1.5
mashumaro==3.13.1
matplotlib-inline==0.1.7
mdurl==0.1.2
minimal-snowplow-tracker==0.0.2
more-itertools==10.3.0
msgpack==1.0.8
names==0.3.0
networkx==3.2.1
numpy==1.26.2
ordered-set==4.1.0
packaging==24.1
pandas==2.1.3
parsedatetime==2.6
parso==0.8.4
pathspec==0.12.1
pexpect==4.9.0
prompt_toolkit==3.0.48
protobuf==4.25.3
ptyprocess==0.7.0
pure_eval==0.2.3
pyarrow==14.0.1
pydantic==2.8.2
pydantic_core==2.20.1
Pygments==2.18.0
python-dateutil==2.8.2
python-dotenv==1.0.1
python-slugify==8.0.4
pytimeparse==1.1.8
pytz==2023.3.post1
PyYAML==6.0.1
referencing==0.35.1
regex==2024.9.11
requests==2.32.3
rich==13.9.2
rpds-py==0.19.0
ruamel.yaml==0.18.6
ruamel.yaml.clib==0.2.8
six==1.16.0
sniffio==1.3.1
sqlglot==25.24.5
sqlglotrs==0.2.12
sqlmesh==0.126.1
sqlparse==0.5.1
sse-starlette==2.1.3
stack-data==0.6.3
starlette==0.37.2
text-unidecode==1.3
traitlets==5.14.3
typing_extensions==4.12.2
tzdata==2023.3
tzlocal==5.2
urllib3==2.2.2
uvicorn==0.22.0
uvloop==0.20.0
watchfiles==0.24.0
wcwidth==0.2.13
websockets==13.1
widgetsnbextension==4.0.13
zipp==3.19.2

**Comment by tobymao** [comment]
can you share the code please? and the full stack trace using the cli

**Comment by tobymao** [comment]
i think this is a dbt error, the dbt adapter uses dbt. because dbt doesn't parse sql, it's going to have these limitations and there's not much we can do about it. if you switch to sqlmesh native format, you won't have these issues.
