### ISSUE TITLE
Feature: Fabric Support

### ISSUE THREAD

**Issue by nperez31** [TobikoData/sqlmesh#3264]
Would love to see Fabric added as an engine adapter. Excited to have column level lineage for my Fabric projects.

**Comment by treysp** [comment]
Hello and thanks for the suggestion. Unfortunately, Fabric seems to have a [number of limitations relative to SQL Server](https://learn.microsoft.com/en-us/fabric/data-warehouse/tsql-surface-area#limitations), and some of those are used in core SQLMesh operations. If there is sufficient demand, it may be possible to add Fabric once those limitations are addressed.

**Comment by treysp** [comment]
FYI - I may have closed this prematurely (sorry about that). See discussion in https://github.com/TobikoData/sqlmesh/issues/3374
