### ISSUE TITLE
Clickhouse: can't create functions in pre statements

### ISSUE THREAD

**Issue by jwhitaker-gridcog** [TobikoData/sqlmesh#3276]
With the following model:

```sql
model (
	name my_db.my_model,
	kind view
);

create or replace function jarrad_test as (x) -> x;

select
	1 as x;
```

I get a plan error:
 Code: 1. DB::Exception: Lambda must have valid arguments. (UNSUPPORTED_METHOD) (version 24.6.1.4609 (official build))

I tried to get the executed sql from this but it doesn't show up in `system.query_log`, I'm not sure why but suspect unrelated clickhouse weirdness.

**Comment by treysp** [comment]
Hello, thanks for reporting this. I just round-tripped this in sqlglot, and it's generating as:
```
>>> from sqlglot import parse_one
>>> parse_one("create or replace function jarrad_test as (x) -> x;", dialect="clickhouse").sql("clickhouse")

'CREATE OR REPLACE FUNCTION jarrad_test AS JSONExtractString((x), x)'
```

So it looks like sqlglot is treating the function definition `(x) -> x` like it would if the same thing were in a `SELECT`. We'll look into this.

**Comment by treysp** [comment]
As a temporary workaround, I believe wrapping it as jinja will work:

```
model (
	name my_db.my_model,
	kind view
);

JINJA_STATEMENT_BEGIN;

create or replace function jarrad_test as (x) -> x;

JINJA_END;

select
	1 as x;
```

**Comment by jwhitaker-gridcog** [comment]
thanks all!
