### ISSUE TITLE
Python-based definition of SQL models do not evaluate variables

### ISSUE THREAD

**Issue by alunarbeach** [TobikoData/sqlmesh#3280]
**Issue**
When a SQL with sqlmesh variables is  passed into a python based definition, the model is not evaluating the variables.

**Screenshot**

1. A Variable "min_trigger_id" is  defined
<img width="835" alt="Screenshot 2024-10-22 at 6 19 46 PM" src="https://github.com/user-attachments/assets/acee6226-5d3d-4789-9261-afa7126c69fa">

2. Create a Python-based definition of a model in SQLMesh Example project
<img width="978" alt="Screenshot 2024-10-22 at 6 18 14 PM" src="https://github.com/user-attachments/assets/b44fa46e-bee7-4876-be78-0da373e58a45">

3. Compile Query is still having the variables instead of the values
<img width="995" alt="Screenshot 2024-10-22 at 6 18 34 PM" src="https://github.com/user-attachments/assets/38e52038-cd38-4062-bb7a-ed0fe1faf6e7">

**Comment by tobymao** [comment]
python models don't automatically replace variables, you can do this yourself with the evaluator

for example something like this

`evaluator.transform(evaluator.parse_one(sql))`

**Comment by alunarbeach** [comment]
Thanks @tobymao  for the quick turn around. I got an error stating macro variable is undefined. Do i need to pass any additional argument?  (The SQL model was able to identify the variable).

<img width="1267" alt="image" src="https://github.com/user-attachments/assets/066bfc02-7fd5-4f1d-955f-b0e9619a53bc">

**Comment by tobymao** [comment]
you haven't defined min_trigger_id anywhere, wat you're trying to do is not super standard, i'd suggest removing this and just using string replacament.

```
def entrypoint(...):
     return f"""
     SELECT ..., {min_trigger_id}
     """

```

and then pass that in somehow, or you gateway/variables

https://sqlmesh.readthedocs.io/en/stable/concepts/macros/sqlmesh_macros

**Comment by alunarbeach** [comment]
Sorry @tobymao  I am not following.  
I have defined it in config.yaml .  You can see it in the first screenshot.  Still it's not detecting it.
If the model is a plain SQL file, the min_trigger_id is replaced with the actual value.

This example is a simplistic representation of our actual usecase where string replacement will not be the preferred way.

**Comment by georgesittas** [comment]
@alunarbeach why are you parsing & invoking the the transform method on the evaluator? Not quite sure I understand the intention here. SQLMesh will automatically parse & do that transformation for you at runtime whenever needed.

**Comment by georgesittas** [comment]
Ah, I just saw the rest of the discussion, apologies. Let me take a quick look..

**Comment by alunarbeach** [comment]
Thanks @georgesittas  
The actual use case is we have a ton of plain SQLs in a folder, and I am trying to use SQLMesh for unit testing these SQLs by creating models from Python definition without changing the original SQLs.

**Comment by tobymao** [comment]
@alunarbeach you need to use context.var("min_trigger_id") to access the var, you can then pass that into your string replacement

otherwise you need to instantiate the sql model with the variables take a look at test_model.py::test_variables in the code base

**Comment by georgesittas** [comment]
@alunarbeach this is one way to make it work, albeit not very pretty:

```python
from sqlmesh.core.model import model

def create_model(model_name, sql):

    @model(model_name, is_sql=True, kind="FULL")
    def entrypoint(evaluator):
        evaluator.var("min_trigger_id")
        return evaluator.transform(evaluator.parse_one(sql))

create_model("test", "SELECT @min_trigger_id AS trigger_id")
```

The `evaluator.var(...)` call is injected in the `entrypoint` so that SQLMesh will detect the usage of that variable and hydrate the model's environment with it. Otherwise, it won't know you're using it, so the variable will not be included.

I'm not sure if this pattern is right for this use case, thought. If you have a lot of SQL files and each of those uses different variables, then I suppose you can't know these variables statically to mimic this `evaluator.var(...)` call.

For more advanced use cases you could hook into the `Loader` class and override `_load_sql_models` to do something like what Toby suggested.

**Comment by alunarbeach** [comment]
Thanks again @georgesittas / @tobymao and this is a good workaround for us.

Still, we miss the feature parity mismatch between SQL Models and python based definition.
