### ISSUE TITLE
For INCREMENTAL_BY_UNIQUE_KEY, add an option to DO NOTHING when matched

### ISSUE THREAD

**Issue by dmat** [TobikoData/sqlmesh#3313]
To support insert-only use cases, please provide an option to do nothing when the key is matched.
when_matched WHEN MATCHED THEN DO NOTHING

**Comment by tobymao** [comment]
is this not solved with a custom when_matched expression? 

https://sqlmesh.readthedocs.io/en/stable/concepts/models/model_kinds/?h=matched#when-matched-expression

**Comment by dmat** [comment]
Do you mean something like this:
when_matched WHEN MATCHED AND FALSE THEN UPDATE SET

So, the update never gets executed.

**Comment by tobymao** [comment]
or when matched then update a.id = a.id or something

**Comment by dmat** [comment]
That works too. Wouldn't it cause an additional operation? I'm trying to avoid the UPDATE altogether and only do INSERT.

**Comment by tobymao** [comment]
if it can be done with a custom when match, then i think that would work for you. but this sounds like there's an option for this so closing.

**Comment by tobymao** [comment]
i'm not too familiar with duckdb's merge statement.
