### ISSUE TITLE
global variables don't pass to python models when python model defined with kw-only syntax

### ISSUE THREAD

**Issue by Ben-Epstein** [TobikoData/sqlmesh#3345]
With a model defined as
```py

@model(
    "example.foo",
    columns={
        "ts": "datetime",
        "id": "int",
        "foo": "str"
    },
    kind=ModelKindName.FULL,
)
def execute(
    context: ExecutionContext,
    start: datetime,
    end: datetime,
    execution_time: datetime,
    *,
    custom_mult: int = 1,
    **kwargs: Any,
) -> pd.DataFrame:
```

if I set a variable in my config
```yaml
variables:
  custom_mult: 5
```

it won't get passed through, even though sqlmesh specifies that these are always [passed as keyword-only arguments](https://sqlmesh.readthedocs.io/en/stable/concepts/models/python_models/#global-variables).
> Please note that arguments must be specified explicitly; in other words, variables can be accessed using kwargs.

If i remove the `*`, then it passes through as expected. I think this would be nice functionality to add because it allows python models to be represented semantically correctly, mapping to how they are used

**Comment by treysp** [comment]
@izeigerman Should "variables can be accessed using kwargs" be "variables CANNOT be accessed using kwargs" here?

**Comment by izeigerman** [comment]
> If i remove the *, then it passes through as expected. I think this would be nice functionality to add because it allows python models to be represented semantically correctly, mapping to how they are used

I guess that's the core issue here.

@treysp not sure how `kwargs` are relevant.
