### ISSUE TITLE
sql model seems to call macro even when `@IF` conditional is false

### ISSUE THREAD

**Issue by Ben-Epstein** [TobikoData/sqlmesh#3360]
I have the following macro

```py
from sqlmesh import macro
from sqlmesh.core.macros import MacroEvaluator

@macro(metadata_only=True)
def test_macro(evaluator: MacroEvaluator):
    print("EVAL STAGE", evaluator.runtime_stage)
    return "1"
```

and the following sql model
```sql
MODEL (
    name sqlmesh_example.foo,
    kind INCREMENTAL_BY_TIME_RANGE(
        time_column ts
    ),
    cron '@daily',
    grain (id, ts),
    table_format "delta",
  );

  SELECT id, ts, mean(value)  mean_value
  FROM delta_scan('./ext_table1')
  GROUP BY id, ts
  ORDER BY id, ts;

  @IF(
    @runtime_stage = 'evaluating',
    @test_macro()
  );
```

When I run any command, for example `sqlmesh fetchdf 'select * from sqlmesh_example.foo'`, I see the print
```
EVAL STAGE loading
```

It seems like bug to me, but am I missing something or making a very silly mistake?

Thanks!

**Comment by z3z1ma** [comment]
I don't think SQLMesh has short circuiting during the rendering phase where these macros are expanded. I think it could be hand rolled for @IF but would not be trivial (I think). 

The alternative currently is to move the if statement to the body of the macro in Python.

**Comment by tobymao** [comment]
the if statement is only used for the return value, so test_macro() is called, but it won't be returned as a part of the sql. i'd just move the if statement to the macro as @z3z1ma suggested

**Comment by Ben-Epstein** [comment]
@tobymao can you update the documentation [here](https://sqlmesh.readthedocs.io/en/stable/concepts/models/sql_models/#optional-prepost-statements) to reflect that? This section implies that the macro shouldn't run

<img width="726" alt="image" src="https://github.com/user-attachments/assets/b5162b5c-1243-4b73-9569-d07aba1832a2">

**Comment by georgesittas** [comment]
I think this section is fine. The statement _does_ run only once, it won't be sent to the engine at load time. I can see how there's some ambiguity, but I believe we should address it by saying that `@IF` doesn't short-circuit, as Alex mentioned.
