### ISSUE TITLE
Support `@quarterly` `cron` and `quarter` `interval_unit`

### ISSUE THREAD

**Issue by plaflamme** [TobikoData/sqlmesh#3368]
We'd like to run a model on the first day of each quarter and have the interval set accordingly. We can do this manually, but it'd be nicer if this was out of the box, .e.g.:

```sql
MODEL(
  name foo.once_per_quarter
  kind INCREMENTAL_BY_TIME_RANGE(time_column the_quarter),
  cron '@quarterly',
  interval_unit 'quarter'
);
SELECT @start_date AS the_quarter FROM underlying
```

**Comment by tobymao** [comment]
@plaflamme want to add this?

**Comment by tobymao** [comment]
Can't you just do cron '0 0 1 */3 *' ?

**Comment by plaflamme** [comment]
> Can't you just do cron '0 0 1 */3 *' ?

Yes, but the interval will be `month` which means you also need to add `batch_size 3` to have quarterly intervals... not a huge deal, but it's a little cumbersome for users to understand all of that.

**Comment by tobymao** [comment]
you don't really need to set batch size at all, you'd only need it if backfilling is not scalable

**Comment by tobymao** [comment]
I wouldn’t recommend using start date as the quarter, i think that’s an anti pattern. you should probably use functions that represent correct numbers regardless of batch size. i understand what you’re referring to now.

batch size should really only be used for backfill scalability going to close this for now but happy to continue chatting and discussing
