### ISSUE TITLE
--paths flag doesn't support wildcards

### ISSUE THREAD

**Issue by Harmuth94** [TobikoData/sqlmesh#3372]
Currently, the sqlmesh plan command requires explicit specification of each project path using the `-p` flag. This limitation poses challenges for us managing multiple SQLMesh projects (one for each source system) with interdependencies, including downstream aggregation of sources, shared utility projects containing macros and tests.

## Solution
Introduce support for wildcard patterns in the `-p` flag of the sqlmesh plan command. This enhancement would allow users to specify multiple projects efficiently. For example, using `-p all_projects/*` would include all projects within the `all_projects` directory.

**Comment by georgesittas** [comment]
Fixed by linked PR.
