### ISSUE TITLE
Apache Hive / Apache Impala Support

### ISSUE THREAD

**Issue by benjcabalona1029** [TobikoData/sqlmesh#3426]
Apologies, but I can't seem to find it in the documentation. I can't see Hive and Impala in Sqlmesh's execution engine. Does that mean it's not supported?

**Comment by tobymao** [comment]
it is not currently supported and we don't have plans to implement them. but if someone is up for the task, we're willing to accept a well crafted and tested pr

**Comment by benjcabalona1029** [comment]
I just spent my morning toying with the getting started guide, and i really like this tool. I feel I would like to try. :D Is it a matter of implementing something like [here](https://github.com/TobikoData/sqlmesh/tree/main/sqlmesh/core/engine_adapter), or there's complexity?

**Comment by erindru** [comment]
There is some complexity proportionate to how different the engine is from SQLMesh's existing expectations.

As an example, [here's a recent PR](https://github.com/TobikoData/sqlmesh/pull/3154) where we implemented Athena support

Note that SQLGlot support is a prerequisite and iirc there is currently no SQLGlot support for Impala

**Comment by tobymao** [comment]
@benjcabalona1029 if you're serious, i'd start with hive, i don't think that's too difficult. but impala is probably a non starter until sqlglot is added

**Comment by benjcabalona1029** [comment]
Thanks @erindru  and @tobymao I'll try to work on Hive.
