### ISSUE TITLE
Environment snapshots truncated in MySQL

### ISSUE THREAD

**Issue by MikeWallis42** [TobikoData/sqlmesh#3438]
We're currently using:-
* SQLMesh 0.125.6
* SQLGlot 25.24.5
* Schema Version 57
* State management connector - MySQL

After promoting a plan I then got a Pydantic validation error message when reading the state back out because the snapshots stored against the environment was truncated.
I believe this limitation still exists in the latest version after looking at code and issues that have been raised.
For reference we're up to 102 models and 32 external models in the project now.

environment.snapshots is currently implemented as [a text field](https://github.com/TobikoData/sqlmesh/blob/v0.137.1/sqlmesh/core/state_sync/engine_adapter.py#L142) which translates to TEXT in MySQL and is capped at 65,535 characters.
MySQL has different types for TEXT, MEDIUMTEXT and LONGTEXT whereas for Postgres there's just a single TEXT data type which doesn't have different sizes.

I'm considering the following options.
1. If the data types for MySQL for any snapshot field in environments could be transpiled to LONGTEXT somehow whilst not impacting the other engines that can store state.
2. If we should consider migrating our state backend from MySQL to Postgres in the real short term.
3. If the data stored in snapshots for the environment can be less verbose. From what I can tell it looks like the whole of the snapshot information is being duplicated against the environment whereas realistically we only need the primary keys to get the snapshot information from the snapshot table. I can appreciate that this would introduce some complexity and time with needing to join across tables then.

**Comment by tobymao** [comment]
we should change it to long text. a pr would be much appreciated
