### ISSUE TITLE
Are there plans to support polars dataframe in python models? 

### ISSUE THREAD

**Issue by lucharo** [TobikoData/sqlmesh#3439]
It would be a great feature! 

[Narhwals](https://github.com/narwhals-dev/narwhals) might be relevant for dataframe compatibility

**Comment by tobymao** [comment]
you can convert a polars dataframe into a pandas dataframe and it should work. there are no plans since the major warehouses don't support polars out of the box

**Comment by lucharo** [comment]
I see! I thought the python code was run locally. How do the major warehouses support pandas currently? I.e. to whom or where can I complain?

**Comment by tobymao** [comment]
@lucharo you can use polars with sqlmesh, you just need to convert it into a pandas dataframe at the end.

you can chat with snowflake, bigquery, and databricks.
