### ISSUE TITLE
Change in audit and audit failure not captured in subsequent plan

### ISSUE THREAD

**Issue by thenaturalist** [TobikoData/sqlmesh#3461]
I am puzzled and surprised by a pattern of changing code in an audit which is not caught by a plan command. 

Situation:

1. I have an audit called `is_positive`, defined as:
```
AUDIT (
    name is_positive,
  );

  SELECT * FROM @this_model
  WHERE @column < 0;
```

2. I have a model where I call the audit like so:
```
    [...]
    audits (
        is_positive(column := foobar),
    [...]
```

3. I change my audit to inverse the operator from `WHERE @column < 0;` to `WHERE @column > 0;`

4. I run `sqlmesh plan dev`, results in `No differences when compared to 'dev'`.
**Expected behaviour**: 
A) The change in the audit affecting the model is never happening silently, but explicitly. 
B) Immediately during this plan, the updated audit is run against the data and fails as expected.

5. I remove the line `is_positive(column := foobar),` from my model, rerun `sqlmesh plan dev`, forcing a metadata update:
```
Summary of differences against `dev`:
Models:
└── Metadata Updated:
    └── foo.bar
Apply - Virtual Update [y/n]: y
```

6. I re-add my `is_positive(column := foobar),` audit to my model, and rerun `sqlmesh plan dev`, forcing a metadata update again:
```
Summary of differences against `dev`:
Models:
└── Metadata Updated:
    └── foo.bar
Apply - Virtual Update [y/n]: y
```
The audit **still does not fail, despite the changed definition**?

7. I explicitly audit my model with `sqlmesh audit --model foo.bar --start 2024-10-01 --end 2024-10-03` and only then does the audit fail. 
```
MainThread - sqlmesh.core.snapshot.evaluator - WARNING - Audit 'is_positive' for model 'foo.bar' failed.
Got 3448 results, expected 0.
SELECT * FROM (SELECT * FROM "db"."sqlmesh__foo"."bar__3202718574" AS "bar__3202718574" WHERE "time_col" BETWEEN '2024-10-01' AND '2024-10-03') AS "_q_0" WHERE "column" > 0
Audit is warn only so proceeding with execution. (evaluator.py:898)
is_positive on model foo.bar ❌ FAIL [3448].
```

Only now does an audit fail which basically changed two plan runs ago?

**Comment by georgesittas** [comment]
Hey, thanks for the report. We'll look into this shortly.

**Comment by tobymao** [comment]
this should be fixed for sqlmesh -- dbt still needs to be looked at, closing for now

**Comment by thenaturalist** [comment]
@tobymao @georgesittas, thanks for the quick fix! Awesome!
