### ISSUE TITLE
Bigquery: The query is too large

### ISSUE THREAD

**Issue by esciara** [TobikoData/sqlmesh#3472]
## Forenote

This is a significant issue as it raises significantly (in our case 10x) the costs of running SQL transformations using `sqlmesh` on Bigquery.

The reason for this is that Bigquery pricing models (both on On Demand and on Capacity) are fully or partially based on data scanned. Not being able to use `kind EMBEDDED` means that usage we have to use `kind FULL` to force writing to tables (which induces scanning data) or using `kind VIEW`, which clogs up datasets with intermediate views and has a [nesting limit of 16 views](https://cloud.google.com/bigquery/quotas#standard_view_limits).

It also affects speed performance as it requires extra API calls and read/writes.

## Details

On Bigquery, after playing with `sqlmesh` with `kind FULL` models, we started to switch most models to `kind EMBEDDED` for cost and speed improvements. 

As a result, we started to hit very quickly the following errors messages on multiple models : 

```
Error: Failed processing SnapshotId<"projet"."dataset"."table": xxxxxxxxx>. 
400 POST https://bigquery.googleapis.com/bigquery/v2/projects/mvg-iavista-dwh-prod/jobs?prettyPrint=false: 
The query is too large. The maximum standard SQL query length is 1024.00K characters, including comments and white space characters.
```

This is mainly due to the fact that `sqlmesh` (or probably more precisely `sqlglot`) adds a lot of extra words to sql statements. 

For instance, the sql:
```sql
SELECT
    _id,
    id_element_a,
    id_element_b,
    regle_de_deduplication
FROM
    mydataset.all_duplicates_before_221a
```
Will be regenerated in this much longer sql:
```sql
SELECT
  `all_duplicates_before_221a`.`_id` AS `_id`,
  `all_duplicates_before_221a`.`id_element_a` AS `id_element_a`,
  `all_duplicates_before_221a`.`id_element_b` AS `id_element_b`,
  `all_duplicates_before_221a`.`regle_de_deduplication` AS `regle_de_deduplication`
FROM
  `my_project`.`mydataset`.`all_duplicates_before_221a` AS `all_duplicates_before_221a`
```
Is there any way to change this?

**Comment by tobymao** [comment]
No, I'd suggest using a view instead as that should have the same performance implications as embedded but with split up queries.

**Comment by esciara** [comment]
Ah. As mentioned, we are hitting the nested limit of 16 views, and the dataset becomes full of unwanted view, which becomes confusing to the users and also has an impact on our data catalog...

To me that is a non-negligeable drawback compared to `dbt` (sorry to mention), where we could chain a lot transformations neatly separated in models without having any issue...

Absolutely no way to change this? Even with some help? If guess this is a change on sqlglot?

**Comment by tobymao** [comment]
you’ll hit this in dbt as well so it’s not like the fix is permanent. you’ll eventually hit that limit no matter what.

**Comment by esciara** [comment]
Hi,

I tried to gather some hard facts and this is what I came up with.

## `sqlmesh`

I used `kind EMBEDDED` on all models in my processing chain until I came up with the error (the error cropped up at the 20th step of a total of 53 steps).

Then I ran a `sqlmesh render --no-format MODEL` to get roughly the sql that would be sent to Bigquery, and removed all double spaces (because I noticed that sqlmesh would send the sql query without extra spaces or linebreaks).

I ended up with a file with a size of 1,5 MB, which is coherent with the issue. For further statistics, it had 1,499,346 characters.

<img width="746" alt="image" src="https://github.com/user-attachments/assets/e900ec89-5004-46b3-bca3-3a6d8211c638">
<img width="297" alt="image" src="https://github.com/user-attachments/assets/64cc8304-db90-4c8f-b447-b8582457ed8a">

## `dbt`

I transferred the whole processing chain to `dbt` and I ran the entire chain (all 53 steps), which passed.

I then looked at the jobs history in Bigquery's console, and copy/pasted the sql code, without removing any extra spaces or linebreaks.

I ended up with a file with a size of 34k (so it was well under the 1024 KB), so there is plenty of room for a lot more transformations. For further statistics, it had 33,855 characters (including the extra, not useful spaces).

<img width="755" alt="image" src="https://github.com/user-attachments/assets/678903dd-ec06-42ce-872c-3065f8a4fdcb">
<img width="252" alt="image" src="https://github.com/user-attachments/assets/b8284e59-516d-47fb-8fe7-cf1b92e55cf8">

## Conclusion

So it is highly unlikely that I will hit this limit with `dbt`. I am not pointing that to favor `dbt`. I pointing that because I want to use `sqlmesh` and because, as explained in my forenote, this limit, which is hit very quickly, increases needlessly the cost of running my pipelines, and lengthens artificially processing time.

Could this issue be looked into?

**Comment by tobymao** [comment]
@esciara i could be open to disabling optimizations which would reduce the payload

can you share a snippet of dbt vs sqlmesh so i can compare that it is the problem?

**Comment by tobymao** [comment]
https://github.com/TobikoData/sqlmesh/issues/3479

**Comment by esciara** [comment]
Will work out an example tomorrow if time permits, as the sql I used is confidential (and it is currently night time in Europe). Otherwise, will do as soon as I can.

**Comment by tobymao** [comment]
you can send it to me over slack once you've sanitized it. if it matches my expectations, i'd be happy to work with you to get a PR in to add this option to reduce the payload size by making optimizations optional.

**Comment by esciara** [comment]
Just sent you the sanitized sql.

Maybe this issue should be reopened, should it not?

One thing I saw in the generated sql: it does not seem to use CTEs... Maybe that would be a good idea to systematically use those, as it would avoid quite a few repetiions if an embedded model is used in several other models.

Any questions, don't hesitate.
