### ISSUE TITLE
Is it possible to use pyodbc instead of pymssql?

### ISSUE THREAD

**Issue by SilasFriby** [TobikoData/sqlmesh#3481]
Hi,

not sure if this question should be placed here or not, so feel free to move it elsewhere, or instruct me on what forum the question should be placed in.

Anyway, here we go: Is it in anyway possible to use pyodbc instead of pymssql? I am asking because I am working on a MacBook M3 and there are known issues with pymssql and Mac. For now my solution is to develop my project in a dev container, however I would prefer not to do so.

Best regards
Silas Friby

**Comment by treysp** [comment]
Hello - it is not currently possible to use pyodbc. ODBC driver implementation/support varies a ton across platforms, so no SQLMesh engines use odbc drivers.

SQLMesh should work with pyodbc in principle, though, if you want to switch it. The core connection arg and configuration is [here](https://github.com/TobikoData/sqlmesh/blob/1f0ee529b873d8c63fcb997ad327fd22ba9f38ab/sqlmesh/core/config/connection.py#L1241), but there could be aspects of the [engine code](https://github.com/TobikoData/sqlmesh/blob/main/sqlmesh/core/engine_adapter/mssql.py) that implicitly depend on pymssql's behavior.
