### ISSUE TITLE
Shared ExecutionContext across batches in Python model

### ISSUE THREAD

**Issue by SilasFriby** [TobikoData/sqlmesh#3508]
Hi,

Given the Python model specified below is it then possible to share info across batch runs? Say e.g that I wanted to log a message like f"Running Batch {batch_index}", is it then possilbe to do something like this?

I know that the specific code below will error. I guess because SQLMesh creates an isolated env for each batch run? But anyway, it is possible to somehow share info across batch runs?

Best regards,
Silas

```python
@model(
    "bronze.dms_kontakt_samtale_besked",
    description="Incremental pipeline to copy customer messages from Oracle to SQL Server.",
    kind=dict(
        name=ModelKindName.INCREMENTAL_BY_TIME_RANGE, 
        time_column="oprettet", 
        batch_size=7,  # Number of days per batch
        batch_concurrency=1  # Only run one batch at a time
    ),
    start="2024-11-25",  # Replace with the earliest date for your data
    cron="@daily",  # Set to your desired execution frequency
    columns={
        "besked_id": "int",
        "samtale_id": "int",
        "oprettet": "datetime",
        "sagsbehandler": "string",
        "indhold": "string",
        "_loaded_at": "datetime",
    },
)
def execute(
    context: ExecutionContext,
    start: datetime,
    end: datetime,
    **kwargs
) -> pd.DataFrame:

  batch_index = context.var("batch_index", 0)
  batch_index += 1  # Increment batch index
```

**Comment by tobymao** [comment]
no, i'd probably just do it by the start and end dates. that should give you all the context you need regarding what days are processing

**Comment by SilasFriby** [comment]
Thanks for the quick reply. I am already logging the dates. I was just curios as to whether or not it was possible to share context, so thanks for the clarification.
