### ISSUE TITLE
Cannot use a macro in when matched model config

### ISSUE THREAD

**Issue by MikeWallis42** [TobikoData/sqlmesh#3519]
I'm trying to create a macro to reduce the code within the custom when_matched part of a model definition.
However at the moment I get the following exception when I try to use it.

```
sqlglot.errors.ParseError: Expecting ). Line 2, Col: 7.
  MODEL (
  name [4m@[0mschema_name.obt_appointment_session_v1,
  kind INCREMENTAL_BY_UNIQUE_KEY (
    unique_key (session_i
```

I think I've identified that we defer this straight to sqlglot parsing which obviously does not understand the macros defined by sqlmesh.
Would I be correct in saying that I might need to create a custom parser in sqlmesh to override the sqlglot one to account for macros?
I would definitely welcome some help and guidance in this.

**Comment by georgesittas** [comment]
> Would I be correct in saying that I might need to create a custom parser in sqlmesh to override the sqlglot one to account for macros?

No, this looks unexpected. Sqlglot's parser is patched by sqlmesh so my default expectation is that this should work. Can you share a fully reproducible example so I can try this out?

**Comment by MikeWallis42** [comment]
This is the macro that I've defined, I tried it with both converting to a sql string and leaving it as a sqlmesh expression.

```python
from sqlglot import expressions as exp
from sqlmesh.core.macros import MacroEvaluator, macro

TARGET = "target"
SOURCE = "source"


@macro()
def fingerprint_merge(
        evaluator: MacroEvaluator,
        fingerprint_column: exp.Column,
        update_columns: list[exp.Column],
) -> str:
    """To reduce the amount of SQL needed to be written for custom WHEN MATCHED statements.

    :param evaluator: The sqlmesh MacroEvaluator
    :param fingerprint_column: The name of the column to be used as the fingerprint
    :param update_columns: The list of columns to update on merge
    :return: The name of the gateway as a prefix to the schema.
    """
    fingerprint_evaluation = f"{SOURCE}.{fingerprint_column} <> {TARGET}.{fingerprint_column}"
    column_update = [f"{TARGET}.{column} = {SOURCE}.{column}" for column in update_columns]
    return exp.maybe_parse(
        f"WHEN MATCHED AND {fingerprint_evaluation} THEN UPDATE SET {column_update}",
        into=exp.When,
    ).sql(dialect=evaluator.dialect)
```

The idea behind this is I'm using the surrogate key macro to create a fingerprint for the values in my row as we don't use all columns from the raw table and only want to update our model when a column that we care about has changed.

I tried to articulate the original requirement in this [issue](https://github.com/TobikoData/sqlmesh/issues/2934) hopefully there's something re-usable as an MRE in the comments there?
Please let me know if not.

In terms of usage, in the context of the linked example.
```sql
when_matched @fingerprint_merge(salary, [update_datetime, salary])
```

**Comment by MikeWallis42** [comment]
We're currently using `0.138.0`

**Comment by georgesittas** [comment]
Got it.. The [v0.140.0 release](https://github.com/TobikoData/sqlmesh/releases/tag/v0.140.0) did a major refactor of the `when_matched` property, so maybe this is fixed already, but I'd need to double check. Will take a closer look into this later today, thanks for the report 👍

**Comment by MikeWallis42** [comment]
OK I checked 0.140.0 and I get the same issue. I tried these combinations of returns.

- Convert to str
- Leave as expression
- List of str
- List of expression

**Comment by georgesittas** [comment]
Thank you for checking! I have an idea of what may be causing this issue.
