### ISSUE TITLE
`dlt_load_id` in Generated SQL Doesn't Match dlt Tables

### ISSUE THREAD

**Issue by dat-a-man** [TobikoData/sqlmesh#3545]
I’m working on generating SQLmesh SQL code from a dlt (BlueSky) pipeline using the command:  

```bash
sqlmesh init -t dlt --dlt-pipeline bluesky duckdb
```  
However, I noticed an issue. SQLmesh generates SQL that includes `dlt_load_id` in **all four tables**, but in the dlt pipeline, `dlt_load_id` is only present in **one table**.

**Steps to Reproduce**  
1. After running the dlt pipeline, run the command:  

   ```bash
   sqlmesh init -t dlt --dlt-pipeline bluesky duckdb
   ```  
2. Inspect the generated SQL code for the tables.  

**Expected Behavior**  
`dlt_load_id` should only be present in the table where it exists in the dlt pipeline.  

**Actual Behavior**  
`dlt_load_id` is included in all tables generated by SQLmesh.

**References**  
- Tutorial used: [SQLMesh dlt Pipeline Tutorial](https://davidsj.substack.com/p/sqlmesh-init-t-dlt-dlt-pipeline-bluesky?r=125hnz)
- Related blog post: [dlt-SQLMesh Metadata Handover](https://dlthub.com/blog/sqlmesh-dlt-handover) 
- Documentation: [SQLMesh dlt Integration](https://sqlmesh.readthedocs.io/en/stable/integrations/dlt/?h=dlt)

**Additional Notes**  
This issue seems to relate to improper handling of child tables during SQL generation.  

---

In the database in table, followers__labels
<img width="435" alt="Screenshot 2024-12-20 at 8 49 51 AM" src="https://github.com/user-attachments/assets/7ac4eedb-049b-45b2-9047-c175eec4818d" />

In code there is `dlt_load_id`, originally not in DB
<img width="970" alt="Screenshot 2024-12-20 at 8 50 52 AM" src="https://github.com/user-attachments/assets/ea22ceb3-47ee-45b8-8127-c2e759014d80" />

**Comment by themisvaltinos** [comment]
Thanks for the detailed description in the issue @dat-a-man opened a pr with support for nested dlt tables
