### ISSUE TITLE
Support audits on external models

### ISSUE THREAD

**Issue by djayatillake** [TobikoData/sqlmesh#3552]
I was speaking to someone about things dbt has that sqlmesh doesn't, and should. This came up.

dbt can have source tests to check upstream non-managed models meet contract needed by managed models.

The equivalent for sqlmesh is to be able to audit external models.

**Comment by tobymao** [comment]
this is supported already

https://sqlmesh.readthedocs.io/en/stable/concepts/models/external_models/?h=exter#external-audits
