### ISSUE TITLE
allow_partials false should check data exists

### ISSUE THREAD

**Issue by djayatillake** [TobikoData/sqlmesh#3553]
When allow_partials is false it is still possible for a time interval to be run with no source data available for it. 

A check should run ahead of model run/plan to see if source data exists beyond the end of the time interval to be run. If this check fails then the model and dependents should skip and warn.

**Comment by tobymao** [comment]
you’re looking for signals 

https://sqlmesh.readthedocs.io/en/stable/guides/signals/?h=signal
