### ISSUE TITLE
Add more pre-canned audits

### ISSUE THREAD

**Issue by izeigerman** [TobikoData/sqlmesh#523]
Potential candidates:
- Column values are keys in some other table.
- The column value is above or below a static threshold.
- The column overall average / P50 / P95 / etc. is above or below a static threshold.

**Comment by foundinblank** [comment]
Couple other suggestions: 

* Unique combination of columns 
* No empty strings `""`

**Comment by tobymao** [comment]
closing this for now as alex has contributed a ton
