### ISSUE TITLE
Wrong Slack link in README.md?

### ISSUE THREAD

**Issue by davhin** [TobikoData/sqlmesh#637]
Hey, just stumbled upon this, it seems the Slack link in the README.md is only for users with an @tobikodata address? The wording to me implies otherwise.

The link I found on Twitter and the one on the website work fine, so maybe I'm just wrong but it tripped me up when I tried to join the Slack from GitHub and I thought the signup was not intended to be open yet :)

**Comment by tobymao** [comment]
thanks for the report, we're looking at this now!

**Comment by lamalex** [comment]
Hi, this isn't fixed!

**Comment by vchan** [comment]
> Hi, this isn't fixed!

@lamalex Sorry about that. The Slack link expires every 400 use and has to be updated. Thank you for reporting it.

**Comment by tobymao** [comment]
thank you, updated
