### ISSUE TITLE
sqlmesh init is not working

### ISSUE THREAD

**Issue by SumanthPuram** [TobikoData/sqlmesh#658]
I tried to init the project but that keeps failing. Attaching a screenshot here. 
It doesn't work with virtualenv and also with default python installation.
<img width="862" alt="Screenshot 2023-04-06 at 4 53 21 PM" src="https://user-images.githubusercontent.com/7383674/230363160-dba3d381-852e-480f-b730-f15d796a2b3a.png">

**Comment by GeorgeSittas** [comment]
Hello,

I wasn't able to reproduce this issue locally. Can you share what version of Pydantic you're using? For example:

```python
>>> import pydantic
>>> pydantic.VERSION
'1.10.2'
```

**Comment by SumanthPuram** [comment]
Does this fix also update the python package `sqlmesh`? 
Do I need to build the binary from source? What's the quickest way for me to try out this

**Comment by tobymao** [comment]
pip install --upgrade pydantic
