### ISSUE TITLE
New SQLmesh plan is failing

### ISSUE THREAD

**Issue by SumanthPuram** [TobikoData/sqlmesh#672]
Tried creating a new project and following this [quick start guide](https://sqlmesh.readthedocs.io/en/stable/quick_start/)
```
❯ mkdir sqlmesh-test
❯ cd sqlmesh-test
❯ ls
❯ sqlmesh init
❯ ls
audits      config.yaml macros      models      tests
❯ sqlmesh plan
Error: 4 validation errors for Config
connections -> concurrent_tasks
  Discriminator 'type_' is missing in value (type=value_error.discriminated_union.missing_discriminator; discriminator_key=type_)
connections -> database
  none is not an allowed value (type=type_error.none.not_allowed)
connections -> type_
  Discriminator 'type_' is missing in value (type=value_error.discriminated_union.missing_discriminator; discriminator_key=type_)
connections
  Discriminator 'type_' is missing in value (type=value_error.discriminated_union.missing_discriminator; discriminator_key=type_)
```

**Comment by tobymao** [comment]
@SumanthPuram what version of pydantic do you have? did you create a virtual environment to install sqlmesh?

**Comment by tobymao** [comment]
i think you have a conflicting pydantic package, SQLMesh 

"pydantic>=1.9.1,<2.0.0"

please follow the guide to use a virtual environment to make sure all of your dependencies are correct

https://sqlmesh.readthedocs.io/en/stable/installation/

if this is not the issue, happy to reopen

**Comment by SumanthPuram** [comment]
It worked with virtual env, probably the issue you pointed out. Thanks!
