### ISSUE TITLE
Contribute to development  Run ide: make web-serve . Commnad not working

### ISSUE THREAD

**Issue by teqsk1514** [TobikoData/sqlmesh#673]
### Issue

As per [documentation](https://sqlmesh.readthedocs.io/en/stable/development/#commands-reference) to Run ide: I can use the command `make web-serve`. But the function name `web-serve` doesn't exit's in the [Makefile](https://github.com/TobikoData/sqlmesh/blob/main/Makefile).

```shell
(python-basic) ➜ sqlmesh git:(main) make web-serve 
make: *** No rule to make target `web-serve'. Stop.
```

### Possible Solutions
1. We can update the [documentation](https://sqlmesh.readthedocs.io/en/stable/development/#commands-reference) page to call the function `make ui-up`. 
2. We can update the Makefile and add a new function 
    ```
   web-serve: ui-up 
   ```

- [x] I'm willing to submit a PR!

**Comment by tobymao** [comment]
sure please make one!

**Comment by teqsk1514** [comment]
Sure
