### ISSUE TITLE
Harden Engine Adapters

### ISSUE THREAD

**Issue by eakmanrq** [TobikoData/sqlmesh#676]
With 6 engines now implemented, it is a good time to refactor, cleanup, and harden the engine adapters. Some key goals:

* Organize the methods (alphabetical and grouped public/private)
* Establish the public interface
* Have complete unit test coverage
* Have complete integration tests for all engines
   * We can decide later how to automate this. Ideally it would run before each release
* Make sure everything executed is logged
   * sometimes we call cursor methods directly and therefore execution is not logged

**Comment by tobymao** [comment]
can we not call cursor methods directly

**Comment by eakmanrq** [comment]
This is minimized currently but sometimes the cursors have native ways to help workaround nuances of the engine. So to avoid it would involve copy/pasting their cursor implementation over. We can look at it during the refactor and see how often this is and the complexity of copying it over. If it is rare/complexity is low then I'm aligned with doing that. I'm saying that if we don't do that though then we need to make sure it is at least logged.
