### ISSUE TITLE
`accepted_values` audit requires its `values` parameter to be quoted

### ISSUE THREAD

**Issue by plaflamme** [TobikoData/sqlmesh#702]
for example:
```
audits(
  accepted_values(
    column = my_column,
    "values" = ['Y', 'N']
    )
)
```

Otherwise, you get the following error:

```
Error: Failed to parse a model definition at '...': Required keyword: 'this' missing for <class 'sqlglot.expressions.EQ'>. Line 7, Col: 9.
  ts(
        accepted_values(
            column = my_column
            values = ['Y', 'N']
        )
    )
);

```

**Comment by tobymao** [comment]
values is a keyword in sql. so it's not's not a good choice to use for an argument for the audit function. the fix to this should be to change the kwarg from values to something else

**Comment by plaflamme** [comment]
Sure, I can take a stab at this. Any opinion on the keyword to use instead? Some suggestions: `accepted`, `one_of`, `_values`, `values_`, `accepted_values`, `is_in`

**Comment by tobymao** [comment]
of those, i prefer accepted, one_of, or is_in
