### ISSUE TITLE
Make example project easier to read/understand

### ISSUE THREAD

**Issue by foundinblank** [TobikoData/sqlmesh#707]
Suggestions for improvements to the example models created by `sql init` 

1. Remove the leading `example_` from all model names & files. Since the schema is named `sqlmesh_example` we effectively have `sqlmesh_example.example_incremental_model` which is really clunky. 
2. Add a seed model. So in `./seeds` add `orders.csv` which is basically the values statement in the incremental example, but moved over to a CSV of orders. Then add `seed_model.sql` and define it. Have `incremental model` refer to `seed_model`. Now we have a more complete dag: `orders.csv -> seed_model -> incremental_model -> full_model` 
3. The advantage of this is people can easily edit orders.csv by adding more data, and seeing what happens, rather than directly editing the VALUES() clause in the incremental model. In addition if the CSV contains a wide range of different dates, users will be able to manipulate some more the incremental logic, including seeing what happens to the incremental model if you set different start/end backfill dates -- it all encourages more experimentation 

Bigger ideas: 
1. Have we considered a more real-world project schema, like a basic `analytics.orders -> analytics.revenue`? I think that'd be conceptually faster for new users to pick up on than incremental -> full. 

- [x] I'm happy to submit a PR for either idea or both!

**Comment by tobymao** [comment]
@foundinblank i think this is a great idea and would be grateful if you submit a PR. the bigger idea is great and totally up to you if you want to spend the time to do it.

**Comment by foundinblank** [comment]
Closed by #779!
