### ISSUE TITLE
Databricks: Getting started documentation

### ISSUE THREAD

**Issue by ShanksData** [TobikoData/sqlmesh#719]
I am looking to use SQLMesh with Azure Databricks but the [current documentation](https://github.com/TobikoData/sqlmesh/blob/main/docs/integrations/engines.md#databricks---localbuilt-in-scheduler) does not provide much information on how to get started. 

I want to run SQLMesh from my local environment (Vscode + Python) with a remote connection to Databricks. 

On my local environment, I have installed the dependencies - *sqlmesh* and *sqlmesh[databricks]*, run `sqlmesh init` and then configured the yaml file as follows - 

**config.yaml:**
```
  connections:
      databricks_connection:
          type: databricks
          server_hostname: adb-xxx.azuredatabricks.net
          http_path: sql/protocolv1/o/xxx
          access_token: REDACTED
default_connection: databricks_connection
```

However, I am not sure if these are the right steps. Please advise if existing documentation can be enhanced to support my use case. I am happy to provide additional information or contribute directly if possible.

**Comment by eakmanrq** [comment]
So it sounds like this is your setup:
* Built-in scheduler (not Airflow)
* Python models (not SQL)
* Running locally (not on Databricks cluster)

See this part of the documentation that addresses this: https://github.com/TobikoData/sqlmesh/blob/main/docs/integrations/engines.md#databricks---localbuilt-in-scheduler

Sadly you will need to run [databricks connect](https://docs.databricks.com/dev-tools/databricks-connect.html) locally in order for this to work. The good news is that Databricks Connect is likely going to improve soon since [Spark Connect](https://spark.apache.org/docs/latest/spark-connect-overview.html) was just released with version 3.4. Once that is available then doing this workflow would be significantly improved and I will update the documentation if that is the case.

**Comment by ShanksData** [comment]
Thanks @eakmanrq for the prompt response! Your assumptions are mostly correct. 

However, in addition to running locally, I would also like to run sqlmesh from the notebook directly against my Databricks cluster. I have already read through your documentation for [notebooks](https://sqlmesh.readthedocs.io/en/stable/reference/notebook/) to see how this should be done. But how do I initialize the sqlmesh project when I am running from a notebook? As per instructions, after installing sqlmesh on the cluster, I have to instantiate the context, but first I need a sqlmesh project to point it to. But `sqlmesh init` doesn't work on notebooks.

**Comment by eakmanrq** [comment]
Great point @ShanksData. One option is to call the function directly that `sqlmesh init` calls from within the notebook. So something like this:
```
%python
from sqlmesh.cli.example_project import init_example_project

init_example_project("<local dbfs path>")
```

Then you can use that path in future magic notebook commands.

**Comment by ShanksData** [comment]
@eakmanrq, Thanks for the great tip! 
I will try this out including other options on Databricks and will come back soon.

**Comment by ShanksData** [comment]
I tried this out from the notebooks as suggested. Here are my observations - 

- The example project has 3 config modes, of which it picks up the DEFAULT which uses Duck DB. So even though I am running from within a SparkSession, the execution still happens on Duck DB, which is of course not what I want. How do I get it to use my Spark cluster for executing plans and tests?

-  Few of the magic commands don't seem to work as expected.  For example, I tried to run `%fetchdf "select * from sqlmesh_example.example_incremental_model"` but got an error saying - *TypeError: missing a required argument: 'sql'*. This might be a gap in the documentation.

I realize that some of these may be trivial questions, but so far I don't seem to have got it to work on Databricks with the help of documentation or by reading the source code. If you can point me to the right resource I am happy to dig deeper.

@eakmanrq

**Comment by tobymao** [comment]
for the latter, fetchdf is a cell magic, so you need to do

```
%%fetchdf
select * from ...
```

**Comment by eakmanrq** [comment]
Thanks @ShanksData for the feedback and this is very helpful in helping us understand the gaps in our documentation. 

To change what SQLMesh uses for connection you can define `default_connection` in your config.yaml file. For example you can have something like this:
```
connections:
   duckdb:
       type: duckdb
   databricks:
       type: databricks
       ......
default_connection: databricks
```
You can also explicitly define a connection for running unit tests:
```
test_connection: databricks
```

Therefore you can do something like this to mix connections between unit tests and plan execution:
```
default_connection: databricks
test_connection: duckdb
```

We haven't actually tested running unit tests on something like spark yet so let us know if you have any issues with that.

**Comment by ShanksData** [comment]
Thanks @eakmanrq . Will try that and see how it goes. Meantime I have submitted a PR #734 to update the documentation on Notebooks with some of the discussion in this thread.

**Comment by eakmanrq** [comment]
@ShanksData Looking at the test code a bit more and it looks like we currently do not support running tests on the same engine that you are currently targeting with your models. It could potentially actually be bad to do so since it will drop views that are deploying in your environment when running the test. 

Created an issue here: https://github.com/TobikoData/sqlmesh/issues/752

**Comment by eakmanrq** [comment]
@ShanksData We will be adding native Databricks Connect support (runtime 13.0+ only which uses the new Spark Connect) once this is merged: https://github.com/TobikoData/sqlmesh/pull/860

We created the other issue for the remaining problem of being able to run tests on the same engine as your target connection. So I'm going to close this and you can track  https://github.com/TobikoData/sqlmesh/issues/752 for the status on addressing all your concerns in this issue. Thanks again for creating this and helping with the documentation.
