### ISSUE TITLE
Support sharing connection across unit tests and model targets

### ISSUE THREAD

**Issue by eakmanrq** [TobikoData/sqlmesh#752]
Currently unit tests assume they are running against a connection where they can freely create/drop views. What this means is that if you run the tests against the same connection target as your actual models then you can drop views that are being used in that target environment. Unit tests object should be created in special schemas in order to ensure they don't override actual user facing objects. We should also test different connections and verify unit tests work correctly when completing this issue.

**Comment by GeorgeSittas** [comment]
Closing this in favor of #1637
