### ISSUE TITLE
Support MySQL

### ISSUE THREAD

**Issue by nicosuave** [TobikoData/sqlmesh#765]
My team's current DWH is MySQL protocol compatible— it would be great to see an integration here

**Comment by tobymao** [comment]
what dwh is it? the protocol is only one piece of the puzzle, for example does it support transactions etc.

**Comment by nicosuave** [comment]
Ah makes sense. Singlestore

**Comment by tobymao** [comment]
we don’t really have access to single store since it’s not open source, are you interested in making a pr?

**Comment by nicosuave** [comment]
Sure— the surface looks pretty small for connectors, looking at Postgres for reference.

**Comment by nicosuave** [comment]
FYI this is in progress on my end

**Comment by nicosuave** [comment]
I am throwing in the towel on this one as am decommissioning the relevant datastore soon

**Comment by nicosuave** [comment]
Missed [this](https://github.com/TobikoData/sqlmesh/blob/a85bd3e10bfbce14538f58f3fdb166129603b765/sqlmesh/core/engine_adapter/__init__.py#L26-L27) ha

**Comment by tobymao** [comment]
implemented by #1232
