### ISSUE TITLE
snapshot is a reserved word in redshift and needs to be quoted

### ISSUE THREAD

**Issue by crericha** [TobikoData/sqlmesh#780]
`sqlmesh.core.engine_adapter.base - DEBUG - Executing SQL:
CREATE TABLE IF NOT EXISTS sqlmesh._snapshots (name VARCHAR(MAX), identifier VARCHAR(MAX), version VARCHAR(MAX), snapshot VARCHAR(MAX)) (base.py:761)`

But since 'snapshot' is a reserved word in Redshift, this query fails with a syntax error. We must quote reserved words when using them in column names.

**Comment by bobcolner** [comment]
FYI I just ran into this bug

**Comment by tobymao** [comment]
fixed by https://github.com/tobymao/sqlglot/commit/8440ea4565a626fb65197e8142b99430efbe54ea
