### ISSUE TITLE
Pass [ENVIRONMENT] argument to `evaluate` & `render` commands

### ISSUE THREAD

**Issue by foundinblank** [TobikoData/sqlmesh#797]
I was playing with the `evaluate` and `render` commands and found it counterintuitive that I had to specify the schema too. 

Without schema: 
```bash
>> sqlmesh render full_model
Error: Model `full_model` not found.
```

With schema:
```bash
>> sqlmesh render sqlmesh_example__dev.full_model
_rendered SQL printed here_
```

What I'd really love is to pass the environment name to either command and let SQLMesh take care of the schema for me. Like this: 

```diff 
- sqlmesh render sqlmesh_example__dev.full_model
+ sqlmesh render dev full_model
```

When no environment or schema is specified, have it default to prod schema.

**Comment by cornzyblack** [comment]
Hi, @foundinblank I'll like to work on this issue.

**Comment by tobymao** [comment]
this doesn't really make sense because the name of the model is the fully qualify name, 

sqlmesh_example.full_model
