### ISSUE TITLE
Add support for "tainting" snapshots

### ISSUE THREAD

**Issue by eakmanrq** [TobikoData/sqlmesh#83]
Use case: I have categorized a change in a certain way but I need to change that categorization. Ex: I said something was non-breaking when it is actually breaking. 

The flow is that the user would run a dedicated sqlmesh command to "taint" that snapshot (by telling us the environment and model name). Internally we would create a new snapshot. We haven't decided how we want to do this but it seems like we need to include something as part of the fingerprinting and then by tainting it would create a new fingerprint.

**Comment by tobymao** [comment]
this is implemented with stamp

https://sqlmesh.readthedocs.io/en/stable/concepts/models/overview/#stamp
