### ISSUE TITLE
quickstart example - tables not materialized in duckdb

### ISSUE THREAD

**Issue by ananis25** [TobikoData/sqlmesh#876]
Hi - I followed the quickstart guide [here](https://sqlmesh.readthedocs.io/en/stable/quick_start). Steps taken,
```bash
mkdir sqlmesh-example
cd sqlmesh-example/
sqlmesh init
sqlmesh plan
```

The last step says, "The target environment has been updated successfully", I hope this means all the models have been populated in the duckdb file? However, running the command to view the data yields an empty result for both the `incremental_model` and `full_model` models, while only the seed model seems to be non-empty. 

```bash
sqlmesh fetchdf "select * from sqlmesh_example.incremental_model"

# Empty DataFrame
# Columns:
# Index: []
```

- I confirmed this behavior on both Linux and Mac, using sqlmesh version 0.11.1. 
- Looking into the duckdb file, the physical tables for these models are actually empty, so this doesn't look to be an issue with the `fetchdf` command.

**Comment by tobymao** [comment]
Thanks for the report, the seeds seem to be inserting rows where the date is padding with a space, instead of '2020-01-01' it's ' 2020-01-01'

**Comment by tobymao** [comment]
this is fixed, i'll deploy monday, thanks again for the report
