### ISSUE TITLE
Airflow out of sync if table deleted outside of sqlmesh

### ISSUE THREAD

**Issue by eakmanrq** [TobikoData/sqlmesh#9]
Currently Airflow and the target engine can become out of sync. For example I use Airflow to create prod and then I delete prod in Databricks. SQLMesh will act like the schema and tables in prod still exist and tell me no difference. How do we want to handle that?

Not an immediate issue. This is simply a reminder, so we address later.

**Comment by tobymao** [comment]
out of scope
